### ISSUE TITLE
tracking: insecure downloads

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1003]
Add this active true when ready

[META?] [1654777](https://bugzilla.mozilla.org/show_bug.cgi?id=1654777)

`dom.block_download_insecure` [FF80+]
 - [x] FF82+ [1656296](https://bugzilla.mozilla.org/show_bug.cgi?id=1656296) add indicator
 - [x] FF84+ [1660969](https://bugzilla.mozilla.org/show_bug.cgi?id=1660969) ship panel/button to manually confirm/override block
 - [x] [1662138](https://bugzilla.mozilla.org/show_bug.cgi?id=1662138) "save link as..." on mixed content downloads is silently blocked
 - WONTFIX [1654780](https://bugzilla.mozilla.org/show_bug.cgi?id=1654780) drag and drop bypass

note: telemetry says **about 10% of downloads initiated from secure sites are insecure**

---

### Status

- [x] FF92+ Early Beta [1723783](https://bugzilla.mozilla.org/show_bug.cgi?id=1723783)
   - > In other words, we see that 98.5% of downloads rely on https these days (at least in Nightly).
- [ ] Ride the train [1685479](https://bugzilla.mozilla.org/show_bug.cgi?id=1685479)

### closing

It will happen when it happens
- telemetry shows we're down to 1.5% (from 10%)
- just been extended from nightly to early beta
- HoM upgrades resources - see [1685479#c3](https://bugzilla.mozilla.org/show_bug.cgi?id=1685479#c3)
   - > but you could enable https-only mode which upgrades all resources to https
   - maybe that will help in some cases, IDK
- I tried to replicate 1654780 (drag n drop bypasses), which was closed as WONTFIX, with HoM on windows + `no-deelevate`. Using bugzilla's [site](https://www.thinkbroadband.com/download)... the 5mb test zip, dragging the icon saves me a png, dragging a port link saves me a link `¯\_(ツ)_/¯` .. clicking the links ended up with errors

**Comment by Thorin-Oakenpants** [comment]
OT but secure related: un-breaking sites in HTTPS-only-mode

here's a pretty picture from [1653026](https://bugzilla.mozilla.org/show_bug.cgi?id=1653026) ,,, which landed 36 minutes ago
<img width="473" alt="oooh" src="https://user-images.githubusercontent.com/16656956/95232834-89c90780-07f4-11eb-9972-0da34c2b1f17.png">

**Comment by Thorin-Oakenpants** [comment]
see OP, looks like this will land in FF86

**Comment by Thorin-Oakenpants** [comment]
closing, see OP
