### ISSUE TITLE
tracking: HTTPS-Only mode

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/user.js#1047]
edit: no longer tracking/updating since May 2021

if you see `HOM` in this issue, it this stands for `HTTPS-Only mode`

I've gone through the bugzillas and picked the eyes out. Note that we block mixed active and passive by default, and there is also the upcoming insecure downloads pref: these probably all have a bearing on how this works

update: FF83+ the UI is exposed
- article: https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/

🔻 meta
* [1613063](https://bugzilla.mozilla.org/1613063) meta ticket

🔻 landed

* [x] FF77: [1631384](https://bugzilla.mozilla.org/1631384) loopback / local IP exceptions
* [x] FF78: [1625156](https://bugzilla.mozilla.org/1625156) error page
* [x] FF79: [1640853](https://bugzilla.mozilla.org/1640853) exception (session only via error page)
* [x] FF80: [1647719](https://bugzilla.mozilla.org/1647719) pb mode only pref
* [x] FF80: [1644152](https://bugzilla.mozilla.org/1644152) about:preferences UI
* [x] FF80: [1644456](https://bugzilla.mozilla.org/1644456) exceptions site permissions (basic PageInfo, Site Identity(?))
* [x] FF81: [1651197](https://bugzilla.mozilla.org/1651197) learn more link on error page
* [x] FF81: [1642387](https://bugzilla.mozilla.org/1642387) timing issues -> see 1660945 below
* [x] FF82: [1660945](https://bugzilla.mozilla.org/1660945) privacy stuff
* [x] FF82: [1662359](https://bugzilla.mozilla.org/1662359) subresources when exempted
* [x] FF83: [1647829](https://bugzilla.mozilla.org/1647829) FPI compat
* [x] FF83: [1653026](https://bugzilla.mozilla.org/1653026) give users a way to unbreak a page: site identity panel
* [x] FF83: [1658921](https://bugzilla.mozilla.org/1658921) shiny new dedicated error page
* [x] FF83: [1665062](https://bugzilla.mozilla.org/1665062) upgraded auth
* [x] FF85: [1678614](https://bugzilla.mozilla.org/1678614) trr.mode = 3
* [x] FF86: [1662138](https://bugzilla.mozilla.org/1662138) https-only and blocking mixed content downloads
* [x] FF88: [1665057](https://bugzilla.mozilla.org/1665057) tweak error page
* [x] FF88: [1691888](https://bugzilla.mozilla.org/1691888) break endless upgrade downgrade loops
* [x] FF89: [1658924](https://bugzilla.mozilla.org/1658924) try secure first
* [x] FF90: [1662710](https://bugzilla.mozilla.org/1662710) add preferences UI to manage exceptions
* INVALID [1669424](https://bugzilla.mozilla.org/1669424) propagate exceptions to redirects (yikes?)
* WONTFIX [1661892](https://bugzilla.mozilla.org/1661892) infinite redirects
* WONTFIX [1655329](https://bugzilla.mozilla.org/1655329) IP addresses

🔻 of interest
* [ ] [1647033](https://bugzilla.mozilla.org/1647033) redirects to subdomains
* [ ] [1650779](https://bugzilla.mozilla.org/1650779) redirects
* [ ] [1683015](https://bugzilla.mozilla.org/1683015) 3XX and redirects
* [ ] [1686756](https://bugzilla.mozilla.org/1686756) Insecure downloads taking > 3sec are zero-byte and cancelled - see [comment 7](https://bugzilla.mozilla.org/show_bug.cgi?id=1686756#c7)
* [ ] [1709320](https://bugzilla.mozilla.org/show_bug.cgi?id=1709320) HSTS Response leads to error page

🔻 misc / open
* [1653898](https://bugzilla.mozilla.org/1653898) `www` issues
* [1676227](https://bugzilla.mozilla.org/1676227) consider some kind of clue that an upgrade has happened in the UI

🔻 visuals
- https://mozilla.invisionapp.com/share/R6YJ5KRP7ZM#/screens/429547333

**Comment by earthlng** [comment]
> this can leak things 

correct me if I'm wrong but AFAIK this leak is only really a leak if you use DoH+ESNI.
And even then, if a site is only available over HTTP and you end up adding an HOM exception or click the "go there anyway" button then this can not be considered a leak either.

As I understand it, the background request is also only triggered if a webserver doesn't respond to the HTTPS request within 3 seconds. I only mention this because in another issue @rusty-snake said that this "always leaks" and that's not true AFAIK.
Most servers will probably respond in under 3 seconds.

> we should add this as false to the user.js

we can add it inactive, for people using DoH+ESNI.

**Comment by rusty-snake** [comment]
> As I understand it, the background request is also only triggered if a webserver doesn't respond to the HTTPS request within 3 seconds. I only mention this because in another issue @rusty-snake said that this "always leaks" and that's not true AFAIK.
Most servers will probably respond in under 3 seconds.

_It was [here](https://github.com/arkenfox/user.js/issues/1038#issuecomment-713638864)._

My understanding up to now was that to each server a http and a https connection attempt is made when opening a new site. But thanks to your push I checked this again, and yes it looks like it's only done after 3secs of no response.

https://phabricator.services.mozilla.com/D85300
https://searchfox.org/mozilla-central/source/dom/security/nsHTTPSOnlyUtils.cpp#25

> correct me if I'm wrong but AFAIK this leak is only really a leak if you use DoH+ESNI.

The IP of the site is always leaked w/o a VPN. And the domain is leaked if you don't use DoH/DoT/… and w/o eSNI (which needs to be supported by your firefox and the server) it's leaked too.

As long as background-requets are enabled, a attacker (e.g. your ISP) could delay  all your requests and then catch these http requsts. However, you would note if every site takes much longer.

As HOM now is on about:preferences I wouldn't consider it experimental anymore (as you said). And it works with FPI (but see below). We should add it as `true`  to the user.js. It will upgrade a lot of site which does not have https by default and if you visit one of the ten-site w/o any https, it's  just one click.

FWIW: If you set `privacy.firstparty.isolate.use_site=true` (and FPI), exceptions don't work. (I guess this is expected, since `use_site` makes FPI (and therefore site-permissions/exceptions) reflecting the scheme (i.e. `http://example.com != https://example.com`).

**Comment by earthlng** [comment]
Thanks for mentioning the problem with `use_site`, I wasn't aware of that and I doubt anyone at mozilla is either.
At least I haven't seen a ticket for that yet. AFAICT `use_site` is still in a very early experimental state and breakage is to be expected. But yeah, that's definitely something worth mentioning in our notes/warnings for the HOM pref.

**Comment by Thorin-Oakenpants** [comment]
> If you set `privacy.firstparty.isolate.use_site`=`true` (and FPI), [HTTPS-only mode] exceptions don't work

`privacy.dynamic_firstparty.use_site`, default false in 85 so far, adds scheme to the dFPI key. I guess this *also* adds the scheme to FPI

Has anyone told Mozilla @tomrittervg (or Stephen Englehart or Tim Huang or Gary Chen or @annevk ) that adding the scheme to FPI (and maybe dFPI) breaks HOM exceptions?

- end of tom/anne reading

---

OK, do a PR / draft if you can. I can't follow much of what you guys said and I am sick of bugzilla.

My understanding is
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1642387
 - websites that timeout: e.g. zero response to HTTPS - they timeout after 90 seconds or something
 - so now a background HTTP request is fired at 500ms - potential leak
 - i.e HOM is upgrading to HTTPS first

If we enforce `dom_security_https_only_mode_send_http_background_request` as false
 - now nothing can leak, fuck the timeouts

Explain how it's not a leak. Do you mean because of DNS queries. i.e the background request only leaks the eTLD?

> if a site is only available over HTTP and you end up adding an HOM exception or click the "go there anyway" button then this can not be considered a leak either.

If you **choose** to use an insecure connection, then that's on you. But for those of us who stumble on an HTTP-only site and chose to not go there, we do not want to leak by default and have no say in the matter. I'd rather sites timed out (but see previous question above)

---

I'm too tired. Where did this 3 seconds come from? Did they change the timings?

**Comment by Thorin-Oakenpants** [comment]
ninja'd by E by 1 minute .. but mine was better :)

**Comment by rusty-snake** [comment]
```
/* 1244: enable HTTPS-Only mode [FF76+]
 * When "https_only_mode" (all windows) is true, "https_only_mode_pbm" (private windows only) is ignored
 * [NOTE] If the last pref is true, firefox sends a http requests after 3 seconds of no response to this _domain_
 * to see if the site supports https. This avoids waiting for timeouts.
 * [SETTING] to add site exceptions: Page Info>Permissions>Use insecure HTTP (FF80+)
 * [SETTING] Privacy & Security>HTTPS-Only Mode
 * [1] https://bugzilla.mozilla.org/1613063 [META]
 * [2] https://bugzilla.mozilla.org/1647829 ***/
user_pref("dom.security.https_only_mode", true); // [FF76+]
   // user_pref("dom.security.https_only_mode_pbm", true); // [FF80+]
   // user_pref("dom.security.https_only_mode.upgrade_local", true); // [FF77+]
user_pref("dom.security.https_only_mode_send_http_background_request", false); // [FF82+]
```

> Explain how it's not a leak. Do you mean because of DNS queries. i.e the background request only leaks the eTLD?

Since FF82 it only leaks the domain , but not the site. If `http://example.com/` has no https, then `http://example.com/spam/egg.html` too. And the domain is leaked via DNS if no DoH/DoT is used. And w/o ESNI/ECH it's leaked too. So it's not a real leak if you leak anyway.

**Comment by annevk** [comment]
Could you file a bug on the potential bad interaction between dFPI and HTTPS-only? It's a bit hard to make out what the problem is without context.

**Comment by earthlng** [comment]
@Thorin-Oakenpants 

FYI, these are 2 different prefs!
- `privacy.firstparty.isolate.use_site` controls `use_site` for FPI
- `privacy.dynamic_firstparty.use_site` controls `use_site` for dFPI

> Did they change the timings?

yes they increased it to 3 seconds

**Comment by Thorin-Oakenpants** [comment]
^^ my bad .. I did say I was tired, but I meant *really* tired :) I'm not even sure I even ever knew there were two separate prefs

So we should test
- HOM + dFPI + privacy.dynamic_firstparty.use_site and try exceptions
- HOM + FPI + privacy.firstparty.isolate.use_site and try exceptions

Rusty, please give us the STR for FPI please, including expected outcomes and actual outcomes and site used

---

1244 should be split up into three entries
- enable HOM (2 prefs) + info on use_site
- upgrade locale
- background request

```
 * [NOTE] If the last pref is true, firefox sends a http requests after 3 seconds of no response to this _domain_
 * to see if the site supports https. This avoids waiting for timeouts.
```

That doesn't make sense to me. It sends an HTTP request so it can determine if the site exists so it can fallback to it - not to determine if HTTPS is enabled .. it's already trying that. Unless I'm missing something

PS: we should also remember to note this in the release section for ESR at the top of the user.js
- maybe we could add a 9998 section for ESR flippers

**Comment by rusty-snake** [comment]
STR (used Nightly 85.0a1 (2020-11-18)):

Test sites:
 1. http://speedofanimals.com/ - no https at all (only on www.speedofanimals.com) = timeout
 2. http://neverssl.com/ - bad cert
 3. http://http.badssl.com/ - working https + downgrade using 301 Moved Permanently = infinity loop
 4. http://randomwalker.info/ no https at all = timeout
 5. http://neverssl.org/ - bad cert

NOTE: You need to open the `http` url. If you open a `https` url, HOM is not activated and therefore
you see no warning regarding HOM and you can not add a exception.

Nothing changed (in Nightly this means `network.cookie.cookieBehavior=5` and `privacy.dynamic_firstparty.use_site=true`):
- sites open as expected

Enable HOM (and sanitize cookies, cache, ...):
- see warning "Using HOM - add exception if you want"
- add exception
- site opens using http

Enable FPI (and sanitize):
- same

 Enable `FPI.use_site` (and sanitize):
- see warning "Using HOM - add exception if you want"
- add exception
- see warning "Using HOM - add exception if you want"

**Comment by Thorin-Oakenpants** [comment]
FYI: https://scotthelme.co.uk/firefox-https-only-mode/
- http://httpforever.com/ <- Scott's test site :)

**Comment by crssi** [comment]
I like http://neverssl.org/, because its random, avoiding cache "problems".

**Comment by Thorin-Oakenpants** [comment]
dFPI isn't affected. FWIW, I think we should also add the FPI scheme pref to the user js, inactive, and that way we can refer to it in the HOM section

I [searched](https://github.com/arkenfox/user.js/search?q=use_site&type=issues) this repo for `use_site` and can't even find the release or ticket for when it was added to Firefox

**Comment by rusty-snake** [comment]
@Thorin-Oakenpants  #959

**Comment by Thorin-Oakenpants** [comment]
thanks .. so it's FF78+ then .. also past participle of know is known

**Comment by Thorin-Oakenpants** [comment]
pinning as more bugs and fixes are still happening: I've been keeping OP up to date

**Comment by xtsm** [comment]
So, is there no proper way to add exceptions/whitelists yet?
Because there is no "Use insecure HTTP" line in Permissions tab

**Comment by Thorin-Oakenpants** [comment]
If you use the `continue to HTTP site` button on the notification page, then it's temporary for the Firefox session

If you use the urlbar icon, you can choose to make it permanent
![hom](https://user-images.githubusercontent.com/16656956/113460534-a5f6db80-9408-11eb-8f5c-dbe2ed3d680d.png)

There is [1662710](https://bugzilla.mozilla.org/1662710) where they will add a UI for managing exceptions

**Comment by xtsm** [comment]
It doesn't work with some sites that act like they have a HTTPS version but this version is actually a stub asking you to use HTTP instead (e.g. [this one](https://websdr.space/)). I'm not sure what's the reasoning behind such setups.
Guess I'll wait for the UI, thanks.

**Comment by Thorin-Oakenpants** [comment]
hah `https://www.websdr.space` comes up with a bad cert. NFI what's going on with that site

you could add it manually to permissions.sqlite

So I went to http://www.impawards.com/search.php .. clicked `continue to HTTP site`, **_then_** went to the not secure icon in the url bar and changed it to "Off". Close Firefox, edit the entries in permissions.sqlite, restart Firefox, test
 - e.g. in my case it would be: `http://websdr.space^firstPartyDomain=websdr.space`

![permissions](https://user-images.githubusercontent.com/16656956/113487133-c6c13e80-94a5-11eb-8db4-f60cad4af8f0.png)

I'm about to close FF and edit and restart and test for you .. brb

**Comment by Thorin-Oakenpants** [comment]
works for me: I only needed the one line
![worksforme](https://user-images.githubusercontent.com/16656956/113487373-48fe3280-94a7-11eb-99e9-0b777588c113.png)

**Comment by Thorin-Oakenpants** [comment]
Actually ... wait a minute ... don't go to HTTPS (there isn't one) ... just load http://websdr.space/ and it works fine

**Comment by xtsm** [comment]
Yep, manual SQL insert fixes the issue for websdr.space and several other sites, thanks.

**Comment by Thorin-Oakenpants** [comment]
@xtsm ... https://bugzilla.mozilla.org/show_bug.cgi?id=1662710 landed

**Comment by eleius** [comment]
I was wondering if `HOM` also upgrades insecure sub-requests, like HTTPS Everywhere does? (I'm looking for an alternative that is not list-basted... btw I thought I'd comment here to avoid spamming the issues section)

**Comment by rusty-snake** [comment]
I'm not sure if it upgrades sub-requests. Anyway in the worst case you end up with not loading sub-request due to mixed-content blocking.

https://github.com/arkenfox/user.js/blob/00fa8f1b50dbc717ef9cc702679f3829d91fee05/user.js#L692-L697

**Comment by crssi** [comment]
When I have tested last time looong time ago, when HOM is enabled also mixed passive content is upgraded to HTTPS.
I haven't tested for mixed active content, since its blocked anyway (also as default).

But you can easily test your scenario at `https://mixed.badssl.com/`.

Cheers

**Comment by crssi** [comment]
Even if you set:
``` js
/* 1241  */ user_pref("security.mixed_content.block_display_content", false);
``` 
the `1241` setting is ignored when `HOM` enabled.

![image](https://user-images.githubusercontent.com/17024151/130033181-dbdecb42-432f-433a-ba2a-009220fba18b.png)

As you can see in page source the `IMG` is `HTTP`, but network console clearly shows that `IMG` was downloaded over `HTTPS`

**Comment by eleius** [comment]
> As you can see in page source the `IMG` is requested over `HTTP`, but network console clearly shows that `IMG` was downloaded over `HTTPS`

So it does upgrade mixed content sub-requests, and blocks it if downloading via https is not available?

**Comment by Thorin-Oakenpants** [comment]
HTTPS-First is the one that silently fails and allows insecure
HTTPS-Only mode (HoM) attempts to upgrade everything, and never allows insecure without intervention: it complains on top-level load. If top level is HTTPS it will silently fail sub-resources after upgrading - it literally does what it says HTTPS ONLY

> So it does upgrade mixed content sub-requests, and blocks them if downloading via https is not available?

HoM upgrades everything: [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1709838#c10) says (emphasis mine), and chris makes a point of difference with `HTTPS-First` not upgrading subresources, being top-level loads only
> If `HTTPS-Only` is enabled, **_all_** connections will be upgraded to `https`

There was also another comment Chris made some time after that, but I can't find it, in which I'm almost certain he _did_ state it does upgrade all subresources (and silently fail)

So that's the intent, AFAIK. If you follow the meta ticket, there are still a few holes (not web content itself that I know of: it's edge cases likeTCP, HSTS) and teething issues here and there, and tickets for finishing building tests - I'm not really following it TBH.

HoM should be pretty robust. IDK if HTTPS-E in EASE Mode is it's equal - given that it's limited by WebExt

**Comment by eleius** [comment]
> HTTPS-Only mode (HoM) attempts to upgrade everything, and never allows insecure without intervention: it complains on top-level load. If top level is HTTPS it will silently fail sub-resources after upgrading - it literally does what it says HTTPS ONLY

Excellent, thanks!

**Comment by Thorin-Oakenpants** [comment]
re-opening to remind me: we should add that info to the item in the user.js

**Comment by eleius** [comment]
Btw I'm unable to set exceptions, either from the padlock icon (on/off) or from the "manage exceptions" section in about:preferences#privacy, probably because of FPI as reported by @rusty-snake above. You might want to add this info too.

**Comment by Thorin-Oakenpants** [comment]
worksforme, also where I don't see where rusty snake-eyes g.i. joe said something about FPI, but yes, you need to make sure you exception has the right FPI syntax

can you give me the site that doesn't work for you?

**Comment by Thorin-Oakenpants** [comment]
hmmm, I just tried in Nightly and got this garbage (which doesn't work)
![garbage](https://user-images.githubusercontent.com/16656956/130226676-593b4e33-ec7f-4102-a380-9d8926a182fb.png)

**Comment by eleius** [comment]
> also where I don't see where rusty snake-eyes g.i. joe said something about FPI

Last 3 lines in [this comment](https://github.com/arkenfox/user.js/issues/1047#issuecomment-729769716
)

> can you give me the site that doesn't work for you?

_Any_ http website, e.g. libgen.lc - I add the exception (usually setting to "off" via padlock, I also tried via manage exceptions), shutdown Firefox, and the next time there is no exception listed in "manage exceptions".

Since your example (impawards) also met the same fate, I think one of my addons is deleting them for some reason. I'll have to do some tests...

**Comment by rusty-snake** [comment]
@eleius Either don't set `privacy.firstparty.isolate.use_site=true` or use dFPI.

**Comment by rusty-snake** [comment]
http://http.badssl.com/ -> "continue to HTTP Site" -> Padlock "Not Secure" -> HTTPS-Only mode -> Off

**Comment by rusty-snake** [comment]
If you set a HOM exception from the Padlock, it uses the current site. If you are on `about:httpsonlyerror` it will use `http://example.com^firstPartyDomain=about:httpsonlyerror` (fake syntax) and if you have clicked on "continue to HTTP Site", it will use `http://example.com^firstPartyDomain=example.com`.

**Comment by eleius** [comment]
> Did you set `privacy.clearOnShutdown.siteSettings=true`?

Ah yes. So https exceptions are counted as "site settings".

**Comment by rusty-snake** [comment]
Permissions are site settings.

**Comment by rusty-snake** [comment]
Here's the full list:

```jsm
Ci.nsIClearDataService.CLEAR_PERMISSIONS |
  Ci.nsIClearDataService.CLEAR_CONTENT_PREFERENCES |
  Ci.nsIClearDataService.CLEAR_DOM_PUSH_NOTIFICATIONS |
  Ci.nsIClearDataService.CLEAR_SECURITY_SETTINGS |
  Ci.nsIClearDataService.CLEAR_CERT_EXCEPTIONS
```

https://searchfox.org/mozilla-central/source/browser/modules/Sanitizer.jsm#513-517

**Comment by Thorin-Oakenpants** [comment]
IDK what's going on. In FF** or 89 or 90 it worked, for the impawards site, single upgrades worked with FPI, adding exceptions worked with FPI (e.g. edit in sqlite if needed). When the UI for exceptions came along, it still all worked. It still works in my FF91 main Firefox.

But now it all seems broken with FPI in nightly. Seriously, I am so tired of all this shit (not you guys, but the constantness of all this stuff), that honestly, I think I might just fuck off for a year .. I've almost had it

---

@rusty-snake 

> and if you have clicked on "continue to HTTP Site", it will use http://example.com^firstPartyDomain=example.com

FPI is enabled. Clicking `continue to HTTP` on the interstitial is also broken and just loops
![fpi](https://user-images.githubusercontent.com/16656956/130228837-74b4d49d-d63a-43dd-91d8-2dbee981d9a1.png)

If FPI is disabled, everything seems to work.

**Comment by eleius** [comment]
> ```js
> Ci.nsIClearDataService.CLEAR_CONTENT_PREFERENCES
> ```

Ok I'm setting it to false, I just hope "content preferences" (?) cannot be abused for tracking.

**Comment by Thorin-Oakenpants** [comment]
OK, so it was you clearing site preferences on close, then? right? thank fuck for that.

As for nightly, fuck it. I just tested in my main FF and everything works fine with FPI, so until breakage happens in stable, I do not care. Taking a year off, see you in 2022

**Comment by eleius** [comment]
Oh man, sorry about that...

**Comment by Thorin-Oakenpants** [comment]
> Oh man, sorry about that...

not your fault. I assumed you wouldn't be deleting site exceptions (we don;t in the user.js) because that's rather extreme. And I just jumped to the most logical conclusion that it was one of those weird edge case sites: hence why I asked what it was

> I just hope "content preferences" (?) cannot be abused for tracking.

"content preferences" ? If you mean site exceptions, then no. Exceptions are not global (they are **_literally_** exceptions) so can't be used to help track you, and exceptions are only things like allow/prompt/block things - do a control-I on a page and view permissions

**Comment by eleius** [comment]
> I assumed you wouldn't be deleting site exceptions (we don;t in the user.js) because that's rather extreme.

But I shouldn't have posted here using a customized js, I totally forgot I had switched that one to true.

**Comment by Thorin-Oakenpants** [comment]
pants
> edit: ~~you add the exception via the padlock while you are on the interstitial BEFORE you click `continue to HTTP Site`~~ ignore that

rusty
> f you set a HOM exception from the Padlock, it uses the current site. If you are on about:httpsonlyerror it will use http://example.com^firstPartyDomain=about:httpsonlyerror (fake syntax) and if you have clicked on "continue to HTTP Site", it will use http://example.com^firstPartyDomain=example.com.

sorry rusty, I simply don't use the interface or add exceptions (except the one I have had for ages). We better add that

```
 * [SETTING] to add site exceptions: Padlock>HTTPS-Only mode>On/Off/Off temporarily <-- when on the site u MOFOs
 * [SETTING] Privacy & Security>HTTPS-Only Mode
```

**Comment by Thorin-Oakenpants** [comment]
OK, how is this

@eleius @rusty-snake 

```js
/* 1244: enable HTTPS-Only mode in all windows [FF76+]
 * If the top-level is HTTPS, then insecure subresources are also upgraded, failing silently
 * [SETTING] to add site exceptions: Padlock>HTTPS-Only mode>On <- when on the site
 * [SETTING] Privacy & Security>HTTPS-Only Mode
 * [TEST] http://example.com [upgrade]  <--- RUSTY FIND ME SOMETHING ELSE
 * [TEST] http://neverssl.org/ [no upgrade]
 * [1] https://bugzilla.mozilla.org/1613063 [META] ***/
user_pref("dom.security.https_only_mode", true); // [FF76+]
   // user_pref("dom.security.https_only_mode_pbm", true); // [FF80+]
```

**Comment by rusty-snake** [comment]
```js
/* 1244: enable HTTPS-Only mode in all windows [FF76+]
 * If the top-level is HTTPS, then insecure subresources are also upgraded, failing silently
 * [SETTING] to add site exceptions: Padlock>HTTPS-Only mode>On (After "Continue to HTTP Site")
 * [SETTING] to add site exceptions: click "Continue to HTTP Site", Padlock>HTTPS-Only mode>On
 * [SETTING] Privacy & Security>HTTPS-Only Mode
 * [TEST] http://example.com [upgrade]  <--- RUSTY FIND ME SOMETHING ELSE; Actually every site with correct configured https. However if it is in https://hg.mozilla.org/mozilla-central/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc, it will be upgrade regardless of HOM. Will look for a good one.
 * [TEST] http://neverssl.com/ [no upgrade]  <--- .org is dead
 * [1] https://bugzilla.mozilla.org/1613063 [META] ***/
user_pref("dom.security.https_only_mode", true); // [FF76+]
   // user_pref("dom.security.https_only_mode_pbm", true); // [FF80+]
```

**Comment by Thorin-Oakenpants** [comment]
shit that was meant to be the neverssl one

**Comment by Thorin-Oakenpants** [comment]
wait a second ... http://neverssl.com/ is working
