### ISSUE TITLE
ToDo: diffs FF86-FF87

### ISSUE THREAD

**Issue by earthlng** [arkenfox/user.js#1145]
FF87 is [scheduled](https://wiki.mozilla.org/Release_Management/Calendar) for release March 23rd

[FF87 release notes](https://www.mozilla.org/firefox/87.0/releasenotes/) [when ready]
[FF87 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/87)
[FF87 security advisories](https://www.mozilla.org/security/advisories/mfsa2021-10/)

---

104 diffs ( 60 new, 34 gone, 10 different )
* [x] `2701` option 5 is now ~~always~~ visible (edit: if FPI=false) [1691985](https://bugzilla.mozilla.org/1691985) - https://github.com/arkenfox/user.js/commit/8f1c0044b91e7df4e7f369c71b7aed2a4ba7bdd5
   - pref("browser.contentblocking.reject-and-isolate-cookies.preferences.ui.enabled", true);
- `5000s` - pref("browser.quitShortcut.disabled", false); - https://github.com/arkenfox/user.js/commit/911206eed57d4e389d6ff6df792136c79cc33cc1
-  FYI: flips to true in FF89: deal with it in 89 diffs
   -  pref("dom.enable_event_timing", false); [tor 40383](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40383), enabled in all channels FF89+ [1701029](https://bugzilla.mozilla.org/1701029)

### new in v87.0:
```js
pref("browser.urlbar.quicksuggest.enabled", false); // 1691776 Access denied
pref("browser.urlbar.suggest.quicksuggest", true); // ditto
```

### removed, renamed or hidden in  v87.0:
- [x] `ALL DONE` - https://github.com/arkenfox/user.js/commit/b592e0e592bb80141b0b4f880dc3b0069e21301c
   - `0105d` pref("browser.library.activity-stream.enabled", true); [1689405](https://bugzilla.mozilla.org/1689405)
   - `4615` pref("dom.w3c_pointer_events.enabled", true); [1688105](https://bugzilla.mozilla.org/1688105)

### changed in  v87.0:
- [x] `1606` - pref("network.http.referer.defaultPolicy", 2); // prev: 3 [1589074](https://bugzilla.mozilla.org/1589074) - https://github.com/arkenfox/user.js/commit/3b6cd93749f3885b5cbbc54013e7342b6ce995ac
- `5000s` - pref("browser.backspace_action", 2); // prev: 0 [1041377 Part 3](https://bugzilla.mozilla.org/1041377)

---

### ignore

<details><summary>click me for details</summary><p>

==NEW
```js
pref("apz.nonwr.activate_all_scroll_frames", false);
pref("apz.nonwr.activate_all_scroll_frames_when_fission", false);
pref("apz.prefer_jank_minimal_displayports", true);
pref("apz.wr.activate_all_scroll_frames", false);
pref("apz.wr.activate_all_scroll_frames_when_fission", true);
pref("browser.aboutwelcome.skipFocus", false);
pref("browser.proton.toolbar.version", 0);
pref("browser.urlbar.keepPanelOpenDuringImeComposition", false);
pref("browser.urlbar.showSearchSuggestionsFirst", true);
pref("browser.urlbar.sponsoredTopSites", false);
pref("dom.events.asyncClipboard.clipboardItem", false);
pref("dom.forms.submit.trusted_event_only", false);
pref("dom.quotaManager.directoryRemovalOrRenaming.delayMs", 200);
pref("dom.quotaManager.directoryRemovalOrRenaming.maxRetries", 10);
pref("gfx.color_management.force_srgb", false);
pref("gfx.prefer-x11-egl", false);
pref("gfx.webrender.debug.batched-texture-uploads", true);
pref("gfx.webrender.debug.draw-calls-for-texture-copy", true);
pref("gfx.webrender.fallback.basic", true);
pref("gfx.webrender.fallback.software", false);
pref("gfx.webrender.fallback.software-d3d11", false);
pref("gfx.webrender.prefer-robustness", true);
pref("javascript.options.large_arraybuffers", false);
pref("layout.css.caption-side-non-standard.enabled", false);
pref("layout.css.outline-follows-border-radius.enabled", false);
pref("network.cors_preflight.allow_client_cert", false);
pref("network.dns.limit_253_chars", true);
pref("network.jar.record_failure_reason", true);
pref("network.proxy.reload_pac_delay", 2000);
pref("network.trr.confirmation_telemetry_enabled", true);
pref("network.trr.confirmation_timeout_ms", 6000);
pref("network.trr.odoh.enabled", false);
pref("network.trr.odoh.proxy_uri", "");
pref("network.trr.odoh.target_host", "");
pref("network.trr.odoh.target_path", "");
pref("network.trr.wait-for-confirmation", true);
pref("print.more-settings.open", false);
pref("prompts.windowPromptSubDialog", false);
pref("security.sandbox.content.shadow-stacks-strict", false);
pref("security.sandbox.gmp.shadow-stacks-strict", false);
pref("security.sandbox.gpu.shadow-stacks-strict", false);
pref("security.sandbox.rdd.shadow-stacks-strict", false);
pref("security.sandbox.socket.shadow-stacks-strict", false);
pref("services.sync.prefs.sync.browser.urlbar.resultBuckets", true);
pref("services.sync.prefs.sync.browser.urlbar.showSearchSuggestionsFirst", true);
pref("telemetry.fog.test.activity_limit", 120);
pref("telemetry.fog.test.inactivity_limit", 1200);
pref("timer.ignore_sleep_wake_notifications", false);
pref("widget.gtk.non-native.round-thumb", true);
pref("widget.gtk.non-native.scrollbar.allow-buttons", false);
pref("widget.gtk.non-native.scrollbar.normal-size", 12);
pref("widget.gtk.non-native.scrollbar.thin-size", 6);
pref("widget.gtk.non-native.scrollbar.thumb-cross-size", 40);
pref("widget.gtk.non-native.scrollbar.thumb-size", "0.75");
pref("widget.non-native.use-theme-accent", false);
```

==REMOVED or HIDDEN
```js
pref("browser.cache.cache_isolation", false);
pref("browser.preferences.exposeHTTPSOnly", true);
pref("browser.urlbar.imeCompositionClosesPanel", true);
pref("devtools.inspector.new-rulesview.enabled", false);
pref("devtools.target-switching.enabled", true);
pref("dom.events.asyncClipboard.dataTransfer", false);
pref("dom.expose-incomplete-stylesheets", false);
pref("dom.formdata.event.enabled", true);
pref("dom.forms.requestsubmit.enabled", true);
pref("dom.w3c_pointer_events.multiprocess.android.enabled", true);
pref("javascript.options.off_thread_parse_global", false);
pref("layers.advanced.basic-layer.enabled", false);
pref("layers.advanced.fission.enabled", false);
pref("layers.mlgpu.enable-buffer-cache", true);
pref("layers.mlgpu.enable-buffer-sharing", true);
pref("layers.mlgpu.enable-clear-view", true);
pref("layers.mlgpu.enable-cpu-occlusion", true);
pref("layers.mlgpu.enabled", false);
pref("layers.mlgpu.enable-depth-buffer", false);
pref("layers.mlgpu.enable-invalidation", true);
pref("layers.mlgpu.enable-on-windows7", true);
pref("layout.css.focus-visible.enabled", true);
pref("network.tcp.tcp_fastopen_consecutive_failure_limit", 5);
pref("network.tcp.tcp_fastopen_enable", false);
pref("network.tcp.tcp_fastopen_http_check_for_stalls_only_if_idle_for", 10);
pref("network.tcp.tcp_fastopen_http_stalls_limit", 3);
pref("network.tcp.tcp_fastopen_http_stalls_timeout", 20);
pref("network.trr.early-AAAA", false);
pref("network.trr.wait-for-A-and-AAAA", true);
pref("services.sync.prefs.sync.browser.urlbar.matchBuckets", true);
pref("ui.use_native_colors", true);
pref("webgl.oop.via-pcq", false);
```

==CHANGED
```js
pref("browser.topsites.useRemoteSetting", true); // prev: false
pref("devtools.inspector.color-scheme-simulation.enabled", true); // prev: false
pref("dom.input_events.beforeinput.enabled", true); // prev: false
pref("media.cubeb.wasapi-raw", 0); // prev: 1
pref("media.videocontrols.keyboard-tab-to-all-controls", true); // prev: false
pref("permissions.isolateBy.privateBrowsing", true); // prev: false
pref("print.tab_modal.enabled", true); // prev: false
pref("security.allow_parent_unrestricted_js_loads", false); // prev: true
```

</p></details>

**Comment by earthlng** [comment]
<details><summary>some bugzilla tickets</summary><p>

* apz.nonwr.activate_all_scroll_frames
Bug [1690433](https://bugzilla.mozilla.org/show_bug.cgi?id=1690433). Create a minimal display port type.

* apz.nonwr.activate_all_scroll_frames_when_fission
Bug [1690433](https://bugzilla.mozilla.org/show_bug.cgi?id=1690433). Create a minimal display port type.

* apz.prefer_jank_minimal_displayports
Bug [1690433](https://bugzilla.mozilla.org/show_bug.cgi?id=1690433). Prefer to jank minimal display ports until we can set a proper display port over checkerboarding them.

* apz.wr.activate_all_scroll_frames
Bug [1675547](https://bugzilla.mozilla.org/show_bug.cgi?id=1675547). Force layerization for all scrollframes that want it, when WR and fission is enabled.
Bug [1690433](https://bugzilla.mozilla.org/show_bug.cgi?id=1690433). Create a minimal display port type.

* apz.wr.activate_all_scroll_frames_when_fission
Bug [1675547](https://bugzilla.mozilla.org/show_bug.cgi?id=1675547). Force layerization for all scrollframes that want it, when WR and fission is enabled.
Bug [1690433](https://bugzilla.mozilla.org/show_bug.cgi?id=1690433). Create a minimal display port type.

* browser.aboutwelcome.skipFocus
Bug [1692227](https://bugzilla.mozilla.org/show_bug.cgi?id=1692227) - Add ExperimentFeature to newnewtab/settings panel

* browser.backspace_action
Bug [1041377](https://bugzilla.mozilla.org/show_bug.cgi?id=1041377) - Part 3: Disable Backspace as keyboard shortcut for back/forward navigation on Windows and macOS.

* browser.cache.cache_isolation
Bug [1687618](https://bugzilla.mozilla.org/show_bug.cgi?id=1687618) - Remove browser.cache.cache_isolation

* browser.contentblocking.reject-and-isolate-cookies.preferences.ui.enabled
Bug [1691985](https://bugzilla.mozilla.org/show_bug.cgi?id=1691985) - Enable cookieBehavior 5 dropdown option in custom category for beta and release channel.

* browser.library.activity-stream.enabled
Bug [1689405](https://bugzilla.mozilla.org/show_bug.cgi?id=1689405): remove components of library panel

* browser.preferences.exposeHTTPSOnly
Bug [1690276](https://bugzilla.mozilla.org/show_bug.cgi?id=1690276) - Remove unused pref browser.preferences.exposeHTTPSOnly
Bug [1658267](https://bugzilla.mozilla.org/show_bug.cgi?id=1658267) - Expose HTTPS-Only Mode in about:preferences for release users.

* browser.proton.toolbar.version
Bug [1686523](https://bugzilla.mozilla.org/show_bug.cgi?id=1686523), remove home button if proton is enabled and the button hasn't been used

* browser.quitShortcut.disabled
Bug [52821](https://bugzilla.mozilla.org/show_bug.cgi?id=52821) - Add a pref to disable the quit application shortcut.

* browser.topsites.useRemoteSetting
Bug [1693055](https://bugzilla.mozilla.org/show_bug.cgi?id=1693055) - Let top sites remote settings backend ride the 87 release train.
Bug [1681290](https://bugzilla.mozilla.org/show_bug.cgi?id=1681290) - Enable remote setting backend for top sites by default in Nightly 87.

* browser.urlbar.imeCompositionClosesPanel
Bug [1685991](https://bugzilla.mozilla.org/show_bug.cgi?id=1685991) - Change default value of IME composition pref and add it to Nightly Experiments.
Bug [1673971](https://bugzilla.mozilla.org/show_bug.cgi?id=1673971) - Add a pref to show search suggestions during IME composition in the address bar.

* browser.urlbar.keepPanelOpenDuringImeComposition
Bug [1685991](https://bugzilla.mozilla.org/show_bug.cgi?id=1685991) - Change default value of IME composition pref and add it to Nightly Experiments.

* browser.urlbar.quicksuggest.enabled
Bug [1691776](https://bugzilla.mozilla.org/show_bug.cgi?id=1691776) - Implement a QuickSuggest Urlbar provider

* browser.urlbar.showSearchSuggestionsFirst
Bug [1688786](https://bugzilla.mozilla.org/show_bug.cgi?id=1688786) - Add a browser.urlbar.showSearchSuggestionsFirst pref.

* browser.urlbar.sponsoredTopSites
Bug [1695747](https://bugzilla.mozilla.org/show_bug.cgi?id=1695747) - Remove sponsored top sites from address bar results.

* browser.urlbar.suggest.quicksuggest
Bug [1691776](https://bugzilla.mozilla.org/show_bug.cgi?id=1691776) - Implement a QuickSuggest Urlbar provider

* devtools.inspector.color-scheme-simulation.enabled
Bug [1692272](https://bugzilla.mozilla.org/show_bug.cgi?id=1692272) - Enable color-scheme simulation on the Inspector for all channels.
Bug [1692271](https://bugzilla.mozilla.org/show_bug.cgi?id=1692271) - Enable color-scheme simulation on the Inspector only in Nightly.
Bug [1679408](https://bugzilla.mozilla.org/show_bug.cgi?id=1679408) - Enable color-scheme simulation on the inspector.

* devtools.inspector.new-rulesview.enabled
Bug [1676419](https://bugzilla.mozilla.org/show_bug.cgi?id=1676419) - [devtools] Remove the react based rule view

* devtools.target-switching.enabled
Bug [1689559](https://bugzilla.mozilla.org/show_bug.cgi?id=1689559) - [devtools] Remove devtools.target-switching.enabled preference
Bug [1663649](https://bugzilla.mozilla.org/show_bug.cgi?id=1663649) - [devtools] Enable target switching by default.

* dom.enable_event_timing
Bug [1667836](https://bugzilla.mozilla.org/show_bug.cgi?id=1667836) - Implement PerformanceEventTiming Interface

* dom.events.asyncClipboard.clipboardItem
Bug [1619947](https://bugzilla.mozilla.org/show_bug.cgi?id=1619947) - Implement ClipboardItem skeleton code

* dom.events.asyncClipboard.dataTransfer
Bug [1689886](https://bugzilla.mozilla.org/show_bug.cgi?id=1689886) - Add a test-only clipboard.read implementation with ClipboardItem.

* dom.expose-incomplete-stylesheets
Bug [1687127](https://bugzilla.mozilla.org/show_bug.cgi?id=1687127) - Remove dom.expose-incomplete-stylesheets.

* dom.formdata.event.enabled
Bug [1690897](https://bugzilla.mozilla.org/show_bug.cgi?id=1690897) - Get rid of `dom.formdata.event.enabled` pref;

* dom.forms.requestsubmit.enabled
Bug [1690888](https://bugzilla.mozilla.org/show_bug.cgi?id=1690888) - Get rid of `dom.forms.requestsubmit.enabled` pref;

* dom.forms.submit.trusted_event_only
Bug [1370630](https://bugzilla.mozilla.org/show_bug.cgi?id=1370630) - Untrusted submit event shouldn't trigger form submission;

* dom.input_events.beforeinput.enabled
Bug [1665530](https://bugzilla.mozilla.org/show_bug.cgi?id=1665530) - Make `beforeinput` event and `InputEvent.getTargetRanges()` ride the train
Bug [1677390](https://bugzilla.mozilla.org/show_bug.cgi?id=1677390) - Flip dom.innerSize.rounded back to true for causing web compat issues.

* dom.quotaManager.directoryRemovalOrRenaming.delayMs
Bug [1693741](https://bugzilla.mozilla.org/show_bug.cgi?id=1693741) - Retry removing or renaming of origin directories in StorageOperationBase::MaybeRenameOrigin;

* dom.quotaManager.directoryRemovalOrRenaming.maxRetries
Bug [1693741](https://bugzilla.mozilla.org/show_bug.cgi?id=1693741) - Retry removing or renaming of origin directories in StorageOperationBase::MaybeRenameOrigin;

* dom.w3c_pointer_events.enabled
Bug [1688105](https://bugzilla.mozilla.org/show_bug.cgi?id=1688105) - Part 2: Get rid of dom.w3c_pointer_events.enabled;

* dom.w3c_pointer_events.multiprocess.android.enabled
Bug [1688105](https://bugzilla.mozilla.org/show_bug.cgi?id=1688105) - Part 1: Get rid of dom.w3c_pointer_events.multiprocess.android.enabled;
Bug [1682527](https://bugzilla.mozilla.org/show_bug.cgi?id=1682527) - Enable implicit pointer capture for touch on Nightly channel;

* gfx.color_management.force_srgb
Bug [1678487](https://bugzilla.mozilla.org/show_bug.cgi?id=1678487) - Remove SRGBOverrideObserver, and make gfx.color_management.force_srgb a static pref.

* gfx.prefer-x11-egl
Bug [1680512](https://bugzilla.mozilla.org/show_bug.cgi?id=1680512) - Prefer EGL for glxtest detection and fallback to GLX if unavailable.

* gfx.webrender.debug.batched-texture-uploads
Bug [1690247](https://bugzilla.mozilla.org/show_bug.cgi?id=1690247) - Enable the batched texture upload path on windows.
Bug [1681310](https://bugzilla.mozilla.org/show_bug.cgi?id=1681310) - Add a batched texture upload code path using glTexSubImage2D.

* gfx.webrender.debug.draw-calls-for-texture-copy
Bug [1690247](https://bugzilla.mozilla.org/show_bug.cgi?id=1690247) - Enable the batched texture upload path on windows.
Bug [1681310](https://bugzilla.mozilla.org/show_bug.cgi?id=1681310) - Add a batched texture upload code path using glTexSubImage2D.

* gfx.webrender.fallback.basic
Bug [1689203](https://bugzilla.mozilla.org/show_bug.cgi?id=1689203) - Allow fallback from WebRender to Software WebRender.

* gfx.webrender.fallback.software
Bug [1689203](https://bugzilla.mozilla.org/show_bug.cgi?id=1689203) - Allow fallback from WebRender to Software WebRender.

* gfx.webrender.fallback.software-d3d11
Bug [1689203](https://bugzilla.mozilla.org/show_bug.cgi?id=1689203) - Allow fallback from WebRender to Software WebRender.

* gfx.webrender.prefer-robustness
Bug [1680759](https://bugzilla.mozilla.org/show_bug.cgi?id=1680759) - Enable EGL robustness with WebRender on Linux.

* javascript.options.large_arraybuffers
Bug [1688616](https://bugzilla.mozilla.org/show_bug.cgi?id=1688616) part 1 - Add a browser pref for large ArrayBuffers.

* javascript.options.off_thread_parse_global
Bug [1690115](https://bugzilla.mozilla.org/show_bug.cgi?id=1690115) - Remove off_thread_parse_global preference
Bug [1667804](https://bugzilla.mozilla.org/show_bug.cgi?id=1667804) - Enable stencil-mvp pref.

* layers.advanced.basic-layer.enabled
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.advanced.fission.enabled
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-buffer-cache
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-buffer-sharing
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-clear-view
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-cpu-occlusion
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enabled
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.
Bug [1679577](https://bugzilla.mozilla.org/show_bug.cgi?id=1679577) - Disable advanced layers pref.

* layers.mlgpu.enable-depth-buffer
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-invalidation
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layers.mlgpu.enable-on-windows7
Bug [1541472](https://bugzilla.mozilla.org/show_bug.cgi?id=1541472) - Remove Advanced Layers, since it's disabled everywhere now.

* layout.css.caption-side-non-standard.enabled
Bug [1688695](https://bugzilla.mozilla.org/show_bug.cgi?id=1688695) - Hide non-standard values of caption-side.

* layout.css.focus-visible.enabled
Bug [1690225](https://bugzilla.mozilla.org/show_bug.cgi?id=1690225) - Remove focus-visible feature flag.
Bug [1445482](https://bugzilla.mozilla.org/show_bug.cgi?id=1445482) - Enable :focus-visible on all channels for Firefox 85.

* layout.css.outline-follows-border-radius.enabled
Bug [315209](https://bugzilla.mozilla.org/show_bug.cgi?id=315209) - Add a pref to make non-auto outline follow border radius.

* media.cubeb.wasapi-raw
Bug [1684320](https://bugzilla.mozilla.org/show_bug.cgi?id=1684320) - Don't use raw input streams on Windows/WASAPI.

* media.videocontrols.keyboard-tab-to-all-controls
Bug [1681007](https://bugzilla.mozilla.org/show_bug.cgi?id=1681007) - enable keyboard navigation to video controls by default.
Bug [494175](https://bugzilla.mozilla.org/show_bug.cgi?id=494175) part 1: Add a pref to control whether all of the video controls are included in the tab order (default false for now).

* network.cors_preflight.allow_client_cert
Bug [1511151](https://bugzilla.mozilla.org/show_bug.cgi?id=1511151) - Add a flag to allow client certs on CORS preflight connections

* network.dns.limit_253_chars
Bug [1264117](https://bugzilla.mozilla.org/show_bug.cgi?id=1264117) - Limit length of hostnames to 253 characters

* network.http.referer.defaultPolicy
Bug [1589074](https://bugzilla.mozilla.org/show_bug.cgi?id=1589074) - Set referrer policy default to strict-origin-when-cross-origin.

* network.jar.record_failure_reason
Bug [1695560](https://bugzilla.mozilla.org/show_bug.cgi?id=1695560) - Narrow down the zero_byte_load probe.

* network.proxy.reload_pac_delay
Bug [1680688](https://bugzilla.mozilla.org/show_bug.cgi?id=1680688) - Add a delay before we reload PAC url

* network.tcp.tcp_fastopen_consecutive_failure_limit
Bug [1689604](https://bugzilla.mozilla.org/show_bug.cgi?id=1689604) - Remove TCPFastOpen part 3

* network.tcp.tcp_fastopen_enable
Bug [1689604](https://bugzilla.mozilla.org/show_bug.cgi?id=1689604) - Remove TCPFastOpen part 3

* network.tcp.tcp_fastopen_http_check_for_stalls_only_if_idle_for
Bug [1689604](https://bugzilla.mozilla.org/show_bug.cgi?id=1689604) - Remove TCPFastOpen part 3

* network.tcp.tcp_fastopen_http_stalls_limit
Bug [1689604](https://bugzilla.mozilla.org/show_bug.cgi?id=1689604) - Remove TCPFastOpen part 3

* network.tcp.tcp_fastopen_http_stalls_timeout
Bug [1689604](https://bugzilla.mozilla.org/show_bug.cgi?id=1689604) - Remove TCPFastOpen part 3

* network.trr.confirmation_telemetry_enabled
Bug [1694457](https://bugzilla.mozilla.org/show_bug.cgi?id=1694457) - Add pref for reporting confirmation event telemetry

* network.trr.confirmation_timeout_ms
Bug [1691933](https://bugzilla.mozilla.org/show_bug.cgi?id=1691933) - Increase timeout for TRR confirmation request

* network.trr.early-AAAA
Bug [1660975](https://bugzilla.mozilla.org/show_bug.cgi?id=1660975) - Move some TRR prefs to StaticPrefList.yaml
Bug [1691721](https://bugzilla.mozilla.org/show_bug.cgi?id=1691721) - Remove early partial DNS records prefs

* network.trr.odoh.enabled
Bug [1684040](https://bugzilla.mozilla.org/show_bug.cgi?id=1684040) - P1: Introduce new ODoH class for sending ODoH queries

* network.trr.odoh.proxy_uri
Bug [1684040](https://bugzilla.mozilla.org/show_bug.cgi?id=1684040) - P1: Introduce new ODoH class for sending ODoH queries

* network.trr.odoh.target_host
Bug [1684040](https://bugzilla.mozilla.org/show_bug.cgi?id=1684040) - P1: Introduce new ODoH class for sending ODoH queries

* network.trr.odoh.target_path
Bug [1684040](https://bugzilla.mozilla.org/show_bug.cgi?id=1684040) - P1: Introduce new ODoH class for sending ODoH queries

* network.trr.wait-for-A-and-AAAA
Bug [1660975](https://bugzilla.mozilla.org/show_bug.cgi?id=1660975) - Move some TRR prefs to StaticPrefList.yaml
Bug [1691721](https://bugzilla.mozilla.org/show_bug.cgi?id=1691721) - Remove early partial DNS records prefs

* network.trr.wait-for-confirmation
Bug [1689113](https://bugzilla.mozilla.org/show_bug.cgi?id=1689113) - Don't skip TRR unless confirmation explicitly failed.

* permissions.isolateBy.privateBrowsing
Bug [1680237](https://bugzilla.mozilla.org/show_bug.cgi?id=1680237) - Enable permission isolation by private browsing for the release channel.

* print.more-settings.open
Bug [1688099](https://bugzilla.mozilla.org/show_bug.cgi?id=1688099), save more settings state in a pref and honor value on subsequent prints

* print.tab_modal.enabled
Bug [1602410](https://bugzilla.mozilla.org/show_bug.cgi?id=1602410) - Make window.print() work with tab-modal printing.
Bug [1657161](https://bugzilla.mozilla.org/show_bug.cgi?id=1657161), enable print.tab_modal.enabled for EARLY_BETA_OR_EARLIER and hide page range section
Bug [1652627](https://bugzilla.mozilla.org/show_bug.cgi?id=1652627) - Setup a pref for tab modal print UI
Bug [1692232](https://bugzilla.mozilla.org/show_bug.cgi?id=1692232) - Enable tab-modal print UI on all channels
Bug [1680156](https://bugzilla.mozilla.org/show_bug.cgi?id=1680156) - Actually enable pages_per_sheet properly
Bug [1680156](https://bugzilla.mozilla.org/show_bug.cgi?id=1680156) - Enable pages per sheet by default

* prompts.windowPromptSubDialog
Bug [1685313](https://bugzilla.mozilla.org/show_bug.cgi?id=1685313) - allow window modal dialogs to display inside windows,

* security.allow_parent_unrestricted_js_loads
Bug [1688800](https://bugzilla.mozilla.org/show_bug.cgi?id=1688800): Carve out more edge cases for javascriptLoad restrictions, and let Telemetry ride the trains

* security.sandbox.content.shadow-stacks-strict
Bug [1689398](https://bugzilla.mozilla.org/show_bug.cgi?id=1689398) p2: Add prefs to allow CET Strict Mode to be turned on for each sandboxed child process.

* security.sandbox.gmp.shadow-stacks-strict
Bug [1689398](https://bugzilla.mozilla.org/show_bug.cgi?id=1689398) p2: Add prefs to allow CET Strict Mode to be turned on for each sandboxed child process.

* security.sandbox.gpu.shadow-stacks-strict
Bug [1689398](https://bugzilla.mozilla.org/show_bug.cgi?id=1689398) p2: Add prefs to allow CET Strict Mode to be turned on for each sandboxed child process.

* security.sandbox.rdd.shadow-stacks-strict
Bug [1689398](https://bugzilla.mozilla.org/show_bug.cgi?id=1689398) p2: Add prefs to allow CET Strict Mode to be turned on for each sandboxed child process.

* security.sandbox.socket.shadow-stacks-strict
Bug [1689398](https://bugzilla.mozilla.org/show_bug.cgi?id=1689398) p2: Add prefs to allow CET Strict Mode to be turned on for each sandboxed child process.

* services.sync.prefs.sync.browser.urlbar.matchBuckets
Bug [1676469](https://bugzilla.mozilla.org/show_bug.cgi?id=1676469) - Convert matchBuckets to a granular list of result groups and rewrite the muxer to use it.

* services.sync.prefs.sync.browser.urlbar.resultBuckets
Bug [1676469](https://bugzilla.mozilla.org/show_bug.cgi?id=1676469) - Convert matchBuckets to a granular list of result groups and rewrite the muxer to use it.

* services.sync.prefs.sync.browser.urlbar.showSearchSuggestionsFirst
Bug [1688786](https://bugzilla.mozilla.org/show_bug.cgi?id=1688786) - Add a browser.urlbar.showSearchSuggestionsFirst pref.

* telemetry.fog.test.activity_limit
Bug [1690106](https://bugzilla.mozilla.org/show_bug.cgi?id=1690106) - Implement FOG user-activity-based baseline ping schedule

* telemetry.fog.test.inactivity_limit
Bug [1690106](https://bugzilla.mozilla.org/show_bug.cgi?id=1690106) - Implement FOG user-activity-based baseline ping schedule

* timer.ignore_sleep_wake_notifications
Bug [1415923](https://bugzilla.mozilla.org/show_bug.cgi?id=1415923) - Ignore sleep and wake notifications on OSX

* ui.use_native_colors
Bug [1692224](https://bugzilla.mozilla.org/show_bug.cgi?id=1692224) - Remove ui.use_native_colors.

* webgl.oop.via-pcq
Bug [1691606](https://bugzilla.mozilla.org/show_bug.cgi?id=1691606) - Remove dead pref.

* widget.gtk.non-native.round-thumb
Bug [1690700](https://bugzilla.mozilla.org/show_bug.cgi?id=1690700) - Make non-native GTK scrollbars more configurable.

* widget.gtk.non-native.scrollbar.allow-buttons
Bug [1690812](https://bugzilla.mozilla.org/show_bug.cgi?id=1690812) - Allow users to opt-in into scrollbar-buttons on GTK.

* widget.gtk.non-native.scrollbar.normal-size
Bug [1690700](https://bugzilla.mozilla.org/show_bug.cgi?id=1690700) - Make non-native GTK scrollbars more configurable.

* widget.gtk.non-native.scrollbar.thin-size
Bug [1690700](https://bugzilla.mozilla.org/show_bug.cgi?id=1690700) - Make non-native GTK scrollbars more configurable.

* widget.gtk.non-native.scrollbar.thumb-cross-size
Bug [1690700](https://bugzilla.mozilla.org/show_bug.cgi?id=1690700) - Make non-native GTK scrollbars more configurable.

* widget.gtk.non-native.scrollbar.thumb-size
Bug [1690700](https://bugzilla.mozilla.org/show_bug.cgi?id=1690700) - Make non-native GTK scrollbars more configurable.

* widget.non-native.use-theme-accent
Bug [1690778](https://bugzilla.mozilla.org/show_bug.cgi?id=1690778) - Derive accent color from theme highlight color in GTK.

</p></details>

**Comment by Cade66** [comment]
Being no longer able with FF87 to access the old `about:config` format with `chrome://global/content/config.xhtml` is a pain. especially with the `?filter=` feature. I had several filters allowing quick access (mainly to check) which were so useful. I don't understand such aberrations.

**Comment by Thorin-Oakenpants** [comment]
see #1118 ... but seriously .. how often are you in there. Just use the new version and adapt like everyone else

**Comment by Cade66** [comment]
The link is enough no need to waste your time with comments which when non-technical are and remain superfluous.

**Comment by gitthehubs** [comment]
Firefox 87 trims HTTP Referrers by default to protect user privacy
https://blog.mozilla.org/security/2021/03/22/firefox-87-trims-http-referrers-by-default-to-protect-user-privacy/

> The ‘no-referrer-when-downgrade’ policy is a relic of the past web, when sensitive web browsing was thought to occur over HTTPS connections and as such should not leak information in HTTP requests. Today’s web looks much different: the web is on a path to becoming HTTPS-only, and browsers are taking steps to curtail information leakage across websites. It is time we change our default Referrer Policy in line with these new goals.

> Starting with Firefox 87, we set the default Referrer Policy to ‘strict-origin-when-cross-origin’ which will trim user sensitive information accessible in the URL. 

Setting 1606
`// user_pref("network.http.referer.defaultPolicy", 3); // [DEFAULT: 3]`
This is now default 2. (same as for private browsing)

**Comment by iWARR** [comment]
What I have in my own "user.js" :
```
/***	
[ Quick Suggest (Experiment & Telemetry) ]

[SETTING]	Search -> Search Suggestions -> Show suggested and sponsored results in the address bar

A provider that returns a suggested URL to the user based on what they have currently typed so they can navigate directly.
Quick Suggest feature uses "app.support.baseURL" + "firefox-suggest" for the urlFormatter service of the Search provider.
QuickSuggest is only loaded by the UrlBar on it's first query, however it can preload when idle also.
 
[1]	https://searchfox.org/mozilla-central/source/browser/components/urlbar/UrlbarProviderQuickSuggest.jsm
***/

// [MASTER SWITCH] : Quick Suggest = [ Disabled ]
/*	Master switch for the pref state and Telementry events.     */
user_pref("browser.urlbar.quicksuggest.enabled", false);	// added // [DEFAULT = false] // [FF87]

//  [FF OPTIONS] : Quick Suggest listener = [ Disabled ]
/*	This used to listen for URL-BAR changes and recording a Telemetry event, when pref is Disabled/Enabled.
	The pref "browser.urlbar.quicksuggest.enabled" is also need to be listen and depends on it state.
[1]	https://hg.mozilla.org/releases/mozilla-release/rev/1694e4467407472aa7d4d21d7805f55a3e370e58     */
user_pref("browser.urlbar.suggest.quicksuggest", false);	// added // [FF87]
```
Just share this. Feel free to decide what to do with that by you own.
(I don't meet online suggestions, I hate telemetry & experiments, so I've disabled these)

**Comment by Thorin-Oakenpants** [comment]
oh fuck .. I completely forgot about those two I left up there

**Comment by Thorin-Oakenpants** [comment]
Oh that's right ... `browser.urlbar.quicksuggest.enabled` is default false for now

**Comment by Thorin-Oakenpants** [comment]
closing: the master pref is default false, and telemetry is disabled (assuming the telemetry master switch applies: can't be bothered to look)
