### ISSUE TITLE
ToDo: diffs FF89-FF90

### ISSUE THREAD

**Issue by earthlng** [arkenfox/user.js#1206]
FF90 is [scheduled](https://wiki.mozilla.org/Release_Management/Calendar) for release July 13th

[FF90 release notes](https://www.mozilla.org/firefox/90.0/releasenotes/) [when ready]
[FF90 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/90)
[FF90 security advisories](https://www.mozilla.org/security/advisories/)

---

104 diffs ( 61 new, 29 gone, 14 different )

### new in v90.0:
- [x] pref("app.update.background.scheduling.enabled", false); - see [article](https://support.mozilla.org/kb/enable-background-updates-firefox-windows) - https://github.com/arkenfox/user.js/commit/a7ba61c0d4e5af6f63a27b89e73baeb09ba146cb
- [x] FYI: ⚠️ DO NOT USE: experimental and not hooked up - https://github.com/arkenfox/user.js/commit/b761a9dd32f79395b0fca183ad8fe45f7e99d26f
   - read [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1635603#c12) at bugzilla
   - pref("privacy.resistFingerprinting.exemptedDomains", "*.example.invalid");
   - pref("privacy.resistFingerprinting.testGranularityMask", 0);
- FYI: HTTPS-Only mode (see `1244` ) overrides these and is more strict
   - pref("dom.security.https_first", false);
   - pref("dom.security.https_first_pbm", false);

### removed, renamed or hidden in  v90.0:
- [x] DONE - https://github.com/arkenfox/user.js/commit/981462ee54cd627682038b7e5251ae706c7743be and https://github.com/arkenfox/user.js/commit/f229a3cb753e59c06ab9ba43eec455db831ca452
   - `0708` pref("network.ftp.enabled", false); - [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475)
   - `2730` pref("browser.cache.offline.storage.enable", false); - [1694662](https://bugzilla.mozilla.org/show_bug.cgi?id=1694662)

### changed in  v90.0:
- FYI
   - pref("dom.security.secFetch.enabled", true); // prev: false [Fetch_metadata_request_header](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_metadata_request_header)
   - pref("network.http.http3.enabled", true); // prev: false
   - pref("security.osclientcerts.autoload", true); // prev: false [OS Client Certs](https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/)

---

### ignore

<details><summary>click me for details</summary><p>

==NEW
```js
pref("accessibility.cache.enabled", false);
pref("app.update.background.timeoutSec", 600);
pref("browser.aboutwelcome.protonDesign", true);
pref("browser.download.improvements_to_download_panel", false);
pref("browser.low_commit_space_threshold_mb", 200);
pref("browser.privatebrowsing.infoTitleEnabled", true);
pref("browser.privatebrowsing.promoTitleEnabled", true);
pref("browser.topsites.contile.enabled", false);
pref("browser.topsites.contile.endpoint", "https://contile.services.mozilla.com/v1/tiles");
pref("browser.urlbar.quicksuggest.nonSponsoredIndex", -1);
pref("browser.urlbar.quicksuggest.sponsoredIndex", -1);
pref("browser.urlbar.unitConversion.enabled", false);
pref("dom.event.wheelDelta.enabled", true);
pref("dom.events.asyncClipboard.read", false);
pref("dom.mouse_capture.enabled", true);
pref("dom.quotaManager.caching.checkBuildId", true);
pref("dom.w3c_pointer_events.scroll_by_pen.enabled", false);
pref("dom.webnotifications.silent.enabled", false);
pref("dom.webnotifications.vibrate.enabled", false);
pref("gfx.font-list-omt.enabled", false);
pref("gfx.windows-font-substitutes.always", false);
pref("image.avif.compliance_strictness", 1);
pref("image.exif-density-correction.enabled", true);
pref("image.exif-density-correction.sanity-check.enabled", true);
pref("image.jxl.enabled", false);
pref("image.svg.blob-image", false);
pref("javascript.options.concurrent_multiprocess_gcs.cpu_divisor", 4);
pref("javascript.options.concurrent_multiprocess_gcs.max", 0);
pref("javascript.options.experimental.ergonomic_brand_checks", true);
pref("javascript.options.experimental.private_fields", true);
pref("javascript.options.experimental.private_methods", true);
pref("javascript.options.self_hosted.use_shared_memory", true);
pref("layout.css.accent-color.enabled", false); // https://drafts.csswg.org/css-ui-4/#widget-accent
pref("layout.css.moz-control-character-visibility.enabled", false);
pref("layout.extra-tick.minimum-ms", -1);
pref("layout.keep_ticking_after_load_ms", 1000);
pref("mousewheel.system_scroll_override.enabled", true);
pref("mousewheel.system_scroll_override.horizontal.factor", 200);
pref("mousewheel.system_scroll_override.vertical.factor", 200);
pref("network.dns.negative_ttl_for_type_record", 300);
pref("network.http.http3.support_version1", true);
pref("nimbus.debug", false);
pref("pdfjs.enableXfa", false);
pref("places.forgetThisSite.clearByBaseDomain", false);
pref("print.save_as_pdf.links.enabled", true);
pref("privacy.query_stripping.allow_list", "");
pref("privacy.query_stripping.enabled", false);
pref("privacy.query_stripping.redirect", true);
pref("privacy.query_stripping.strip_list", "");
pref("threads.control_event_queue.enabled", true);
pref("toolkit.backgroundtasks.defaultTimeoutSec", 600);
pref("widget.gtk.alt-theme.accent", true);
pref("widget.gtk.alt-theme.dark", false);
pref("widget.gtk.alt-theme.scrollbar", false);
pref("widget.gtk.alt-theme.scrollbar_active", true);
pref("widget.gtk.alt-theme.selection", true);
pref("widget.system-colors-follow-theme", false);
```

==REMOVED or HIDDEN
```js
pref("advanced.mailftp", false);
pref("dom.security.https_only_mode_https_first", false);
pref("dom.security.https_only_mode_https_first_pbm", false);
pref("layout.css.ruby.position-alternate.enabled", true);
pref("media.useAudioChannelAPI", false);
pref("mousewheel.system_scroll_override_on_root_content.enabled", true);
pref("mousewheel.system_scroll_override_on_root_content.horizontal.factor", 200);
pref("mousewheel.system_scroll_override_on_root_content.vertical.factor", 200);
pref("network.ftp.control.qos", 0);
pref("network.ftp.data.qos", 0);
pref("network.ftp.idleConnectionTimeout", 300);
pref("network.proxy.ftp", "");
pref("network.proxy.ftp_port", 0);
pref("pdfjs.enableWebGL", false);
pref("pdfjs.renderer", "canvas");
pref("plugin.mousewheel.enabled", true);
pref("remote.enabled", true);
pref("services.blocklist.pinning.bucket", "pinning");
pref("services.blocklist.pinning.checked", 0);
pref("services.blocklist.pinning.collection", "pins");
pref("services.blocklist.pinning.enabled", true);
pref("services.blocklist.pinning.signer", "pinning-preload.content-signature.mozilla.org");
pref("ui.android.mouse_as_touch", 1);
pref("widget.content.allow-gtk-dark-theme.accent", true);
pref("widget.content.allow-gtk-dark-theme.scrollbar", false);
pref("widget.content.allow-gtk-dark-theme.scrollbar_active", true);
pref("widget.content.allow-gtk-dark-theme.selection", true);
```

==CHANGED
```js
pref("browser.download.viewableInternally.enabledTypes", "xml,svg,webp,avif,jxl"); // prev: "xml,svg,webp,avif"
pref("browser.startup.preXulSkeletonUI", false); // prev: true
pref("canvas.createConicGradient.enabled", true); // prev: false
pref("gfx.webrender.fallback.software.requires-gpu-process", false); // prev: true
pref("gfx.webrender.fallback.software-d3d11", true); // prev: false
pref("intl.charset.detector.ng.in.enabled", true); // prev: false
pref("intl.charset.detector.ng.jp.enabled", true); // prev: false
pref("intl.charset.detector.ng.lk.enabled", true); // prev: false
pref("media.mediacontrol.stopcontrol.timer", true); // prev: false
pref("media.mediacontrol.stopcontrol.timer.ms", 86400000); // prev: 60000
pref("services.sync.engine.tabs.filteredUrls", "^(about:.*|resource:.*|chrome:.*|file:.*|blob:.*|moz-extension:.*)$"); // prev: "^(about:.*|resource:.*|chrome:.*|wyciwyg:.*|file:.*|blob:.*|moz-extension:.*)$"
```

</p></details>

**Comment by earthlng** [comment]
<details><summary>some bugzilla tickets</summary><p>

* accessibility.cache.enabled
Bug [1710976](https://bugzilla.mozilla.org/show_bug.cgi?id=1710976): Add a pref for caching of content process a11y trees in the parent process.

* advanced.mailftp
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* app.update.background.timeoutSec
Bug [1708752](https://bugzilla.mozilla.org/show_bug.cgi?id=1708752) - Allow BackgroundTasksManager to use a timeout to prevent long running tasks

* browser.aboutwelcome.protonDesign
Bug [1711942](https://bugzilla.mozilla.org/show_bug.cgi?id=1711942) - Ungraduate about:welcome from proton pref

* browser.cache.offline.storage.enable
Bug [1694662](https://bugzilla.mozilla.org/show_bug.cgi?id=1694662) - Remove Appcache storage pref

* browser.download.improvements_to_download_panel
Bug [1710929](https://bugzilla.mozilla.org/show_bug.cgi?id=1710929) - Create pref for downloads panel improvements

* browser.download.viewableInternally.enabledTypes
Bug [1707590](https://bugzilla.mozilla.org/show_bug.cgi?id=1707590) - Part 4: Add image/jxl to Accept header and DownloadsViewableInternally

* browser.low_commit_space_threshold_mb
Bug [1711610](https://bugzilla.mozilla.org/show_bug.cgi?id=1711610) - Should not trigger the memory pressure event if the available commit space is not low.

* browser.privatebrowsing.infoTitleEnabled
Bug [1715504](https://bugzilla.mozilla.org/show_bug.cgi?id=1715504) - Banner variations for Private Browsing mode experiment.

* browser.privatebrowsing.promoTitleEnabled
Bug [1715504](https://bugzilla.mozilla.org/show_bug.cgi?id=1715504) - Banner variations for Private Browsing mode experiment.

* browser.startup.preXulSkeletonUI
Bug [1705470](https://bugzilla.mozilla.org/show_bug.cgi?id=1705470) - Flip pref for skeleton UI to ride the trains to release
Bug [1680258](https://bugzilla.mozilla.org/show_bug.cgi?id=1680258) - Enable skeleton UI on nightly

* browser.topsites.contile.enabled
Bug [1707700](https://bugzilla.mozilla.org/show_bug.cgi?id=1707700) - Implement getting sponsored top sites from Contile server rather than remote settings.

* browser.topsites.contile.endpoint
Bug [1707700](https://bugzilla.mozilla.org/show_bug.cgi?id=1707700) - Implement getting sponsored top sites from Contile server rather than remote settings.

* browser.urlbar.quicksuggest.nonSponsoredIndex
Bug [1711792](https://bugzilla.mozilla.org/show_bug.cgi?id=1711792) - Allow quick suggest results to appear at Nimbus-configurable positions within the general bucket.

* browser.urlbar.quicksuggest.sponsoredIndex
Bug [1711792](https://bugzilla.mozilla.org/show_bug.cgi?id=1711792) - Allow quick suggest results to appear at Nimbus-configurable positions within the general bucket.

* browser.urlbar.unitConversion.enabled
Bug [1697722](https://bugzilla.mozilla.org/show_bug.cgi?id=1697722): Implement unit converter as UrlbarProvider.

* canvas.createConicGradient.enabled
Bug [1711724](https://bugzilla.mozilla.org/show_bug.cgi?id=1711724) - Ship CanvasRenderingContext2D.createConicGradient.

* dom.event.wheelDelta.enabled
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Expose WheelEvent.wheelDelta{,X,Y} for compat with other engines.

* dom.events.asyncClipboard.read
Bug [1701512](https://bugzilla.mozilla.org/show_bug.cgi?id=1701512) - Add a separate pref for clipboard.read().

* dom.mouse_capture.enabled
Bug [973604](https://bugzilla.mozilla.org/show_bug.cgi?id=973604) - Mark set/releaseCapture() as deprecated

* dom.quotaManager.caching.checkBuildId
Bug [1702422](https://bugzilla.mozilla.org/show_bug.cgi?id=1702422) - Report failed LoadQuotaFromCache as a warning (instead of an error);

* dom.security.https_first
Bug [1706552](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): Change HTTPS First Mode pref to dom.security.https_first

* dom.security.https_first_pbm
Bug [1706552](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): Change HTTPS First Mode pref to dom.security.https_first

* dom.security.https_only_mode_https_first
Bug [1706552](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): Change HTTPS First Mode pref to dom.security.https_first

* dom.security.https_only_mode_https_first_pbm
Bug [1706552](https://bugzilla.mozilla.org/show_bug.cgi?id=1706552): Change HTTPS First Mode pref to dom.security.https_first

* dom.security.secFetch.enabled
Bug [1695911](https://bugzilla.mozilla.org/show_bug.cgi?id=1695911) - Flip dom.security.secFetch.enabled pref to true.

* dom.w3c_pointer_events.scroll_by_pen.enabled
Bug [1637259](https://bugzilla.mozilla.org/show_bug.cgi?id=1637259) - Dispatch touch event for WM_POINTER

* dom.webnotifications.silent.enabled
Bug [1696145](https://bugzilla.mozilla.org/show_bug.cgi?id=1696145) - Support Notification.silent and .vibrate on Android.

* dom.webnotifications.vibrate.enabled
Bug [1696145](https://bugzilla.mozilla.org/show_bug.cgi?id=1696145) - Support Notification.silent and .vibrate on Android.

* gfx.font-list-omt.enabled
Bug [1708768](https://bugzilla.mozilla.org/show_bug.cgi?id=1708768) - Make InitFontList safe to call off-main-thread on macOS, and run font-list initialization on a separate thread during startup.

* gfx.webrender.fallback.software.requires-gpu-process
Bug [1711118](https://bugzilla.mozilla.org/show_bug.cgi?id=1711118) - Part 2. Allow Software WebRender without the GPU process in release.
Bug [1709476](https://bugzilla.mozilla.org/show_bug.cgi?id=1709476) - Allow falling back to Software WebRender from D3D11/WebRender in release.

* gfx.webrender.fallback.software-d3d11
Bug [1711118](https://bugzilla.mozilla.org/show_bug.cgi?id=1711118) - Part 3. Allow D3D11 compositing with Software WebRender in release.

* gfx.windows-font-substitutes.always
Bug [1716433](https://bugzilla.mozilla.org/show_bug.cgi?id=1716433) - Create a pref to determine whether Windows font substitutes are applied always, or only as fallback for unavailable fonts.

* image.avif.compliance_strictness
Bug [1712368](https://bugzilla.mozilla.org/show_bug.cgi?id=1712368) - update mp4parse-rust to dd96773.

* image.exif-density-correction.enabled
Bug [1680387](https://bugzilla.mozilla.org/show_bug.cgi?id=1680387) - Fix interaction with src-set() / image-set(), and enable the feature by default.
Bug [1680387](https://bugzilla.mozilla.org/show_bug.cgi?id=1680387) - Read and expose EXIF image resolution data.

* image.exif-density-correction.sanity-check.enabled
Bug [1680387](https://bugzilla.mozilla.org/show_bug.cgi?id=1680387) - Sanity-check exif resolution with other exif metadata.

* image.jxl.enabled
Bug [1712147](https://bugzilla.mozilla.org/show_bug.cgi?id=1712147) - Add more missing MOZ_JXL checks
Bug [1711850](https://bugzilla.mozilla.org/show_bug.cgi?id=1711850) - Enable MOZ_JXL only for Nightly builds
Bug [1707590](https://bugzilla.mozilla.org/show_bug.cgi?id=1707590) - Part 2: Implement nsJXLDecoder

* image.svg.blob-image
Bug [1713651](https://bugzilla.mozilla.org/show_bug.cgi?id=1713651) - Turn off recording SVG images in blobs by default.
Bug [1704792](https://bugzilla.mozilla.org/show_bug.cgi?id=1704792) - Part 3. Make display list items request blobs for SVG images.

* intl.charset.detector.ng.in.enabled
Bug [1706864](https://bugzilla.mozilla.org/show_bug.cgi?id=1706864) - Enable chardetng for .in and .lk TLDs.

* intl.charset.detector.ng.jp.enabled
Bug [1711476](https://bugzilla.mozilla.org/show_bug.cgi?id=1711476) - Enable chardetng for the .jp TLD.
Bug [1706864](https://bugzilla.mozilla.org/show_bug.cgi?id=1706864) - Enable chardetng for .in and .lk TLDs.

* intl.charset.detector.ng.lk.enabled
Bug [1706864](https://bugzilla.mozilla.org/show_bug.cgi?id=1706864) - Enable chardetng for .in and .lk TLDs.

* javascript.options.concurrent_multiprocess_gcs.cpu_divisor
Bug [1629064](https://bugzilla.mozilla.org/show_bug.cgi?id=1629064) - pt 4. Add a pref for the maximum number of concurrent GCs

* javascript.options.concurrent_multiprocess_gcs.max
Bug [1629064](https://bugzilla.mozilla.org/show_bug.cgi?id=1629064) - pt 4. Add a pref for the maximum number of concurrent GCs

* javascript.options.experimental.ergonomic_brand_checks
Bug [1710510](https://bugzilla.mozilla.org/show_bug.cgi?id=1710510) - Pref-flip Ergonomic Brand Checks
Bug [1648090](https://bugzilla.mozilla.org/show_bug.cgi?id=1648090) - Add context option for ergnomic brand checks

* javascript.options.experimental.private_fields
Bug [1708235](https://bugzilla.mozilla.org/show_bug.cgi?id=1708235) - Enable Private Fields Preference by default

* javascript.options.experimental.private_methods
Bug [1710510](https://bugzilla.mozilla.org/show_bug.cgi?id=1710510) - Pref-flip Ergonomic Brand Checks
Bug [1708236](https://bugzilla.mozilla.org/show_bug.cgi?id=1708236) - Enable Private Methods Preference by default
Bug [1681046](https://bugzilla.mozilla.org/show_bug.cgi?id=1681046) - Enable Top Level Await by default

* javascript.options.self_hosted.use_shared_memory
Bug [1458339](https://bugzilla.mozilla.org/show_bug.cgi?id=1458339) part 2 - Use shared memory to initialize the JS engine.

* layout.css.accent-color.enabled
Bug [1705605](https://bugzilla.mozilla.org/show_bug.cgi?id=1705605) - Implement accent-color in nsNativeBasicTheme.

* layout.css.moz-control-character-visibility.enabled
Bug [1708384](https://bugzilla.mozilla.org/show_bug.cgi?id=1708384) - Properly hide -moz-control-character-visibility from content.

* layout.css.ruby.position-alternate.enabled
Bug [1708897](https://bugzilla.mozilla.org/show_bug.cgi?id=1708897) - Remove layout.css.ruby.position-alternate.enabled pref.

* layout.extra-tick.minimum-ms
Bug [1708325](https://bugzilla.mozilla.org/show_bug.cgi?id=1708325) - Allow doing an extra refresh driver tick for user input events.

* layout.keep_ticking_after_load_ms
WIP: Bug [1708121](https://bugzilla.mozilla.org/show_bug.cgi?id=1708121), keep ticking after page load

* media.mediacontrol.stopcontrol.timer
Bug [1711590](https://bugzilla.mozilla.org/show_bug.cgi?id=1711590) - Renable deactivate timer and set its expired time to 24hrs.

* media.mediacontrol.stopcontrol.timer.ms
Bug [1711590](https://bugzilla.mozilla.org/show_bug.cgi?id=1711590) - Renable deactivate timer and set its expired time to 24hrs.

* media.useAudioChannelAPI
Bug [1706104](https://bugzilla.mozilla.org/show_bug.cgi?id=1706104) - Remove more references to `media.useAudioChannelAPI`

* mousewheel.system_scroll_override.enabled
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* mousewheel.system_scroll_override.horizontal.factor
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* mousewheel.system_scroll_override.vertical.factor
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* mousewheel.system_scroll_override_on_root_content.enabled
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* mousewheel.system_scroll_override_on_root_content.horizontal.factor
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* mousewheel.system_scroll_override_on_root_content.vertical.factor
Bug [1708829](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829) - Make sure that delta* getters account for scroll speed override correctly.

* network.dns.negative_ttl_for_type_record
Bug [1702332](https://bugzilla.mozilla.org/show_bug.cgi?id=1702332) - Reduce the amount of DNS queries for unavailable type records,

* network.ftp.control.qos
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* network.ftp.data.qos
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* network.ftp.enabled
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs
Bug [1691890](https://bugzilla.mozilla.org/show_bug.cgi?id=1691890) - Let the network.ftp.enabled=false pref change ride the trains

* network.ftp.idleConnectionTimeout
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* network.http.http3.enabled
Bug [1710816](https://bugzilla.mozilla.org/show_bug.cgi?id=1710816) - Enable HTTP/3 by default
Bug [1699490](https://bugzilla.mozilla.org/show_bug.cgi?id=1699490) - Enable HTTP3 on Nightly and beta
Bug [1658362](https://bugzilla.mozilla.org/show_bug.cgi?id=1658362) - Add a pref to set alt-svc mapping artificially for testing.

* network.http.http3.support_version1
Bug [1710821](https://bugzilla.mozilla.org/show_bug.cgi?id=1710821) - Enable HTTP/3 final version by default
Bug [1708567](https://bugzilla.mozilla.org/show_bug.cgi?id=1708567) - Add support for HTTP3 version 1 behind a pref

* network.proxy.ftp
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* network.proxy.ftp_port
Bug [1574475](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475) - Remove ftp prefs

* nimbus.debug
Bug [1707901](https://bugzilla.mozilla.org/show_bug.cgi?id=1707901) - Add opt in to nimbus experiments via URL

* places.forgetThisSite.clearByBaseDomain
Bug [1705028](https://bugzilla.mozilla.org/show_bug.cgi?id=1705028) - Update places forget-this-site to clear storage by base domain.

* plugin.mousewheel.enabled
Bug [1710369](https://bugzilla.mozilla.org/show_bug.cgi?id=1710369) - Remove unused code for dealing with plugins in EventStateManager.

* print.save_as_pdf.links.enabled
Bug [1711064](https://bugzilla.mozilla.org/show_bug.cgi?id=1711064) - patch 1 - Add a pref to control whether linkifying Save-as-PDF output is enabled.

* privacy.query_stripping.allow_list
Bug [1706612](https://bugzilla.mozilla.org/show_bug.cgi?id=1706612) - Part 1: Add a pref for the allow list of query stripping.

* privacy.query_stripping.enabled
Bug [1706607](https://bugzilla.mozilla.org/show_bug.cgi?id=1706607) - Add prefs for the URL query string stripping.

* privacy.query_stripping.redirect
Bug [1706606](https://bugzilla.mozilla.org/show_bug.cgi?id=1706606) - Part 2: Strip target query string for top-level redirects.

* privacy.query_stripping.strip_list
Bug [1706607](https://bugzilla.mozilla.org/show_bug.cgi?id=1706607) - Add prefs for the URL query string stripping.

* privacy.resistFingerprinting.exemptedDomains
Bug [1635603](https://bugzilla.mozilla.org/show_bug.cgi?id=1635603) - Create a nsContentUtils::ShouldResistFingerPrinting(nsIChannel* aChannel)

* remote.enabled
Bug [1710839](https://bugzilla.mozilla.org/show_bug.cgi?id=1710839) - [remote] Remove remote.enabled preference.
Bug [1606604](https://bugzilla.mozilla.org/show_bug.cgi?id=1606604) - [remote] Build the remote agent on all release channels.

* security.osclientcerts.autoload
Bug [1696997](https://bugzilla.mozilla.org/show_bug.cgi?id=1696997) - enable osclientcerts by default in release
Bug [1649518](https://bugzilla.mozilla.org/show_bug.cgi?id=1649518) - 3/3: enable osclientcerts by default in nightly

* services.blocklist.pinning.bucket
Bug [1711599](https://bugzilla.mozilla.org/show_bug.cgi?id=1711599) - remove unused HSTS dynamic preloading implementation

* services.blocklist.pinning.checked
Bug [1711599](https://bugzilla.mozilla.org/show_bug.cgi?id=1711599) - remove unused HSTS dynamic preloading implementation

* services.blocklist.pinning.collection
Bug [1711599](https://bugzilla.mozilla.org/show_bug.cgi?id=1711599) - remove unused HSTS dynamic preloading implementation

* services.blocklist.pinning.enabled
Bug [1711599](https://bugzilla.mozilla.org/show_bug.cgi?id=1711599) - remove unused HSTS dynamic preloading implementation

* services.blocklist.pinning.signer
Bug [1711599](https://bugzilla.mozilla.org/show_bug.cgi?id=1711599) - remove unused HSTS dynamic preloading implementation

* services.sync.engine.tabs.filteredUrls
Bug [1695519](https://bugzilla.mozilla.org/show_bug.cgi?id=1695519) - Remove obsolete checks and references related to wyciwyg protocol.

* threads.control_event_queue.enabled
Bug [1708042](https://bugzilla.mozilla.org/show_bug.cgi?id=1708042), add control priority to the main thread,

* toolkit.backgroundtasks.defaultTimeoutSec
Bug [1708752](https://bugzilla.mozilla.org/show_bug.cgi?id=1708752) - Allow BackgroundTasksManager to use a timeout to prevent long running tasks

* ui.android.mouse_as_touch
Bug [1701269](https://bugzilla.mozilla.org/show_bug.cgi?id=1701269) - Remove ui.android.mouse_as_touch.

* widget.content.allow-gtk-dark-theme.accent
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.
Bug [1701825](https://bugzilla.mozilla.org/show_bug.cgi?id=1701825) - Allow passing some colors from GTK even in dark themes.

* widget.content.allow-gtk-dark-theme.scrollbar
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.
Bug [1701825](https://bugzilla.mozilla.org/show_bug.cgi?id=1701825) - Minor scrollbar tweaks.
Bug [1701825](https://bugzilla.mozilla.org/show_bug.cgi?id=1701825) - Allow passing some colors from GTK even in dark themes.

* widget.content.allow-gtk-dark-theme.scrollbar_active
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.
Bug [1701825](https://bugzilla.mozilla.org/show_bug.cgi?id=1701825) - Minor scrollbar tweaks.

* widget.content.allow-gtk-dark-theme.selection
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.
Bug [1701825](https://bugzilla.mozilla.org/show_bug.cgi?id=1701825) - Allow passing some colors from GTK even in dark themes.

* widget.gtk.alt-theme.accent
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.

* widget.gtk.alt-theme.dark
Bug [1709295](https://bugzilla.mozilla.org/show_bug.cgi?id=1709295) - Keep dark system color extraction behind a pref for now.

* widget.gtk.alt-theme.scrollbar
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.

* widget.gtk.alt-theme.scrollbar_active
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.

* widget.gtk.alt-theme.selection
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.

* widget.system-colors-follow-theme
Bug [1707957](https://bugzilla.mozilla.org/show_bug.cgi?id=1707957) - Extract both light and dark system colors in GTK.

</p></details>

**Comment by earthlng** [comment]
wow, new diff is up for less than 3 hours and you're already almost done with it 👍

**Comment by earthlng** [comment]
`privacy.query_stripping.*` looks interesting. Perhaps that can eventually replace the main functionality of those clear-url extensions

**Comment by gmvk** [comment]
removed `browser.cache.offline.storage.enable`
https://searchfox.org/mozilla-central/search?q=browser.cache.offline.storage.enable

`browser.cache.disk.enable` was not removed
https://searchfox.org/mozilla-central/search?q=browser.cache.disk.enable

 ```
 // The API is easily fingerprinted, use "browser.cache.offline.storage.enable" instead
  // user_pref("browser.cache.offline.enable", false);
```

**Comment by gmvk** [comment]
removed `browser.cache.offline.storage.enable`
https://searchfox.org/mozilla-central/search?q=browser.cache.offline.storage.enable

`browser.cache.offline.enable` was not removed
https://searchfox.org/mozilla-central/search?q=browser.cache.offline.enable

```
// The API is easily fingerprinted, use "browser.cache.offline.storage.enable" instead
 // user_pref("browser.cache.offline.enable", false);
```

**Comment by gmvk** [comment]
removed `browser.cache.offline.storage.enable`
https://searchfox.org/mozilla-central/search?q=browser.cache.offline.storage.enable

`browser.cache.offline.enable` was not removed
https://searchfox.org/mozilla-central/search?q=browser.cache.offline.enable

https://github.com/arkenfox/user.js/commit/981462ee54cd627682038b7e5251ae706c7743be
```
// The API is easily fingerprinted, use "browser.cache.offline.storage.enable" instead
 // user_pref("browser.cache.offline.enable", false);
```

**Comment by Thorin-Oakenpants** [comment]
that's all part of ETP as far as I know based on my gut instincts. The bugzilla you are after is [1697982](https://bugzilla.mozilla.org/show_bug.cgi?id=1697982), and it's not something that was even on their roadmap 4 months ago. That's not to say that it won't morph

**Comment by Thorin-Oakenpants** [comment]
of the rest
- the RFP ones I think we should add inactive with big warnings
- accent-colors: I wanted to check that this didn't leak anything system wide: the spec says undefined uses system accent
- osclientcerts : IDK what this is, for a second I thought it was those os10 ones, but that's FF91 - I think @crssi uses this, and we can probably ignore it
- http3 - it's like HTTP2 all over again (except IDK if there's any privacy issues)

**Comment by Thorin-Oakenpants** [comment]
just waiting on feedback on https://github.com/arkenfox/user.js/commit/3bb9fc713f141d794fc4adfb38d3fcf86c9307ab#commitcomment-53903585

**Comment by Thorin-Oakenpants** [comment]
just waiting on the `0301` issue @earthlng
