### ISSUE TITLE
ToDo: diffs FF96-FF97

### ISSUE THREAD

**Issue by earthlng** [arkenfox/user.js#1366]
FF97 is [scheduled](https://wiki.mozilla.org/Release_Management/Calendar) for release Feb. 8th

[FF97 release notes](https://www.mozilla.org/firefox/97.0/releasenotes/)
[FF97 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/97)
[FF97 security advisories](https://www.mozilla.org/security/advisories/mfsa2022-04/)

---

86 diffs ( 54 new, 14 gone, 18 different )

### new in v97.0:
- [x] `0706` pref("network.proxy.allow_bypass", true); [1733481](https://bugzilla.mozilla.org/show_bug.cgi?id=1733481) now a static pref - https://github.com/arkenfox/user.js/pull/1346/commits/51cc3725112144d0d4fc285a101af70c2afe33e9
   - added in FF95 as a hidden pref - see [this](https://hg.mozilla.org/mozilla-central/diff/d1a755a61abfbb7a3e15c8f941b6fd82924e0a7a/toolkit/modules/ServiceRequest.jsm)
- `7006` pref("dom.securecontext.allowlist_onions", false); [1744006](https://bugzilla.mozilla.org/show_bug.cgi?id=1744006) - replaces "whitelist" pref

### removed, renamed or hidden in  v97.0:
- [x] `7006` pref("dom.securecontext.whitelist_onions", false); - [1744006](https://bugzilla.mozilla.org/show_bug.cgi?id=1744006) - replaced by "allowlist" pref - https://github.com/arkenfox/user.js/pull/1346/commits/35b31a2944fda9c3b7713e7cd468e070932d74cb

### changed in  v97.0:
- [x] pref("dom.vr.enabled", false); // prev: true [1750902](https://bugzilla.mozilla.org/show_bug.cgi?id=1750902) - https://github.com/arkenfox/user.js/pull/1346/commits/850341107d093d6fc025b5d3c5bbcf2bef51a9fb
- FYI: 🎉 [Introducing Site Isolation in Firefox](https://blog.mozilla.org/security/2021/05/18/introducing-site-isolation-in-firefox/)
   - pref("fission.autostart", true); // prev: false
   - pref("fission.autostart.session", true); // prev: false
- FYI: for visibility (in FF95-96 diffs they were flipped to true)
   - pref("network.cookie.sameSite.laxByDefault", false); // prev: true
   - pref("network.cookie.sameSite.noneRequiresSecure", false); // prev: true
   - pref("network.cookie.sameSite.schemeful", false); // prev: true

---

### ignore

<details><summary>click me for details</summary><p>

==NEW
```js
pref("browser.newtabpage.activity-stream.discoverystream.compactGrid.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.compactImages.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.descLines", 3);
pref("browser.newtabpage.activity-stream.discoverystream.editorsPicksHeader.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.essentialReadsHeader.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.hideDescriptions.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.imageGradient.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.newSponsoredLabel.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.readTime.enabled", false);
pref("browser.newtabpage.activity-stream.discoverystream.titleLines", 3);
pref("browser.shell.setDefaultPDFHandler", false);
pref("browser.urlbar.quicksuggest.allowPositionInSuggestions", true);
pref("browser.urlbar.suggest.remotetab", true);
pref("browser.vpn_promo.disallowed_regions", "ae,by,cn,cu,iq,ir,kp,om,ru,sd,sy,tm,tr,ua");
pref("browser.vpn_promo.enabled", true);
pref("devtools.netmonitor.features.newEditAndResend", false);
pref("dom.screenorientation.allow-lock", false);
pref("dom.svg.pathSeg.enabled", false);
pref("dom.webmidi.gated", true);
pref("editor.background_color", "#FFFFFF");
pref("extensions.pocket.refresh.emailButton.enabled", false);
pref("extensions.pocket.refresh.layout.enabled", false);
pref("gfx.webrender.dcomp-video-overlay-win", false);
pref("intl.hyphenation-alias.as", "bn");
pref("intl.hyphenation-alias.as-*", "bn");
pref("intl.hyphenation-alias.bn-*", "bn");
pref("intl.hyphenation-alias.gu-*", "gu");
pref("intl.hyphenation-alias.hi-*", "hi");
pref("intl.hyphenation-alias.kn-*", "kn");
pref("intl.hyphenation-alias.ml-*", "ml");
pref("intl.hyphenation-alias.mr", "hi");
pref("intl.hyphenation-alias.mr-*", "hi");
pref("intl.hyphenation-alias.or-*", "or");
pref("intl.hyphenation-alias.pa-*", "pa");
pref("intl.hyphenation-alias.ta-*", "ta");
pref("intl.hyphenation-alias.te-*", "te");
pref("layout.css.hyphenate-character.enabled", false);
pref("layout.css.named-pages.enabled", false);
pref("layout.oopif_activity_grace_period_ms", 1000);
pref("layout.throttled_frame_rate", 1);
pref("layout.visibility.min-recompute-interval-ms", 1000);
pref("media.audio.playbackrate.muting_threshold", 8);
pref("media.audio.playbackrate.soundtouch_overlap_ms", 8);
pref("media.audio.playbackrate.soundtouch_seekwindow_ms", 15);
pref("media.audio.playbackrate.soundtouch_sequence_ms", 10);
pref("media.videocontrols.picture-in-picture.video-toggle.visibility-threshold", "0.9");
pref("media.webrtc.software_encoder.fallback", true);
pref("network.auth.choose_most_secure_challenge", true);
pref("print.cups.enum_dests_timeout_ms", 150);
pref("print.show_page_setup_menu", false);
pref("widget.disable-swipe-tracker", true);
pref("widget.non-native-theme.win11.scrollbar.force-overlay-style", false);
```

==REMOVED or HIDDEN
```js
pref("browser.proton.enabled", true);
pref("browser.search.update.interval", 21600);
pref("browser.search.update.log", false);
pref("devtools.debugger.tabsBlackBoxed", "[]");
pref("dom.ipc.plugins.sandbox-level.default", 0);
pref("dom.ipc.plugins.sandbox-level.flash", 3);
pref("dom.quotaManager.temporaryStorage.chunkSize", 10240);
pref("fission.openNonFissionWindowOption", false);
pref("layers.acceleration.draw-fps", false);
pref("layout.css.touch_action.enabled", true);
pref("media.videocontrols.picture-in-picture.allow-multiple", true);
pref("print.tab_modal.enabled", true);
pref("privacy.antitracking.cacheStorageAllowedForWindow", true);
```

==CHANGED
```js
pref("app.update.url.manual", "https://www.mozilla.org/%LOCALE%/firefox/new?reason=manual-update"); // prev: "https://www.mozilla.org/%LOCALE%/firefox/"
pref("browser.startup.upgradeDialog.enabled", false); // prev: true
pref("devtools.every-frame-target.enabled", true); // prev: false
pref("devtools.webconsole.input.context", true); // prev: false
pref("dom.w3c_pointer_events.dispatch_by_pointer_messages", true); // prev: false
pref("editor.hr_element.allow_to_delete_from_following_line", true); // prev: false
pref("layout.css.cascade-layers.enabled", true); // prev: false
pref("layout.css.d-property.enabled", true); // prev: false
pref("layout.css.scrollbar-gutter.enabled", true); // prev: false
pref("media.webrtc.platformencoder", true); // prev: false
pref("network.url.max-length", 33554432); // prev: 0
pref("ui.key.textcontrol.prefer_native_key_bindings_over_builtin_shortcut_key_definitions", true); // prev: false
```

</p></details>

**Comment by earthlng** [comment]
<details><summary>some bugzilla tickets</summary><p>

* browser.newtabpage.activity-stream.discoverystream.compactGrid.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.compactImages.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.descLines
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.editorsPicksHeader.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.essentialReadsHeader.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.hideDescriptions.enabled
Bug [1747969](https://bugzilla.mozilla.org/show_bug.cgi?id=1747969) - Fixing Pocket newtab descriptions for remote layouts.

* browser.newtabpage.activity-stream.discoverystream.imageGradient.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.newSponsoredLabel.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.readTime.enabled
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.newtabpage.activity-stream.discoverystream.titleLines
Bug [1746649](https://bugzilla.mozilla.org/show_bug.cgi?id=1746649) - Pocket newtab some new layout prefs

* browser.proton.enabled
Bug [1719939](https://bugzilla.mozilla.org/show_bug.cgi?id=1719939) - remove proton pref from static pref list and its last C++ consumer,
Bug [1699250](https://bugzilla.mozilla.org/show_bug.cgi?id=1699250) - Use proton dark theme in-content

* browser.search.update.interval
Bug [1730875](https://bugzilla.mozilla.org/show_bug.cgi?id=1730875) - Add documentation for search related preferences.

* browser.search.update.log
Bug [1730875](https://bugzilla.mozilla.org/show_bug.cgi?id=1730875) - Add documentation for search related preferences.

* browser.shell.setDefaultPDFHandler
Bug [1743914](https://bugzilla.mozilla.org/show_bug.cgi?id=1743914) - Part 2: Allow to experiment with setting Firefox as default PDF handler on Windows 10+.

* browser.startup.upgradeDialog.enabled
Bug [1738073](https://bugzilla.mozilla.org/show_bug.cgi?id=1738073) - Remove Colorways onboarding when MR2 Colorways expire
Bug [1740623](https://bugzilla.mozilla.org/show_bug.cgi?id=1740623) - Adjust MR2 upgrade spotlight content
Bug [1740819](https://bugzilla.mozilla.org/show_bug.cgi?id=1740819) - Turn off MR2 onboarding in Fx95
Bug [1697222](https://bugzilla.mozilla.org/show_bug.cgi?id=1697222) - Show upgrade dialog without conflicting with existing default browser prompt.

* browser.urlbar.quicksuggest.allowPositionInSuggestions
Bug [1743711](https://bugzilla.mozilla.org/show_bug.cgi?id=1743711): Show allowed sponsored suggestions in second position.

* browser.urlbar.suggest.remotetab
Bug [1746789](https://bugzilla.mozilla.org/show_bug.cgi?id=1746789) - Allow disabling remote tabs in the Urlbar without disabling tab sync.

* browser.vpn_promo.disallowed_regions
Bug [1741741](https://bugzilla.mozilla.org/show_bug.cgi?id=1741741) - Avoid showing Mozilla VPN in unsupported countries

* browser.vpn_promo.enabled
Bug [1741741](https://bugzilla.mozilla.org/show_bug.cgi?id=1741741) - Avoid showing Mozilla VPN in unsupported countries

* devtools.every-frame-target.enabled
Bug [1731740](https://bugzilla.mozilla.org/show_bug.cgi?id=1731740) - [devtools] Enable EFT by default.
Bug [1741808](https://bugzilla.mozilla.org/show_bug.cgi?id=1741808) - [devtools] Enable EFT on Nightly.
Bug [1685500](https://bugzilla.mozilla.org/show_bug.cgi?id=1685500) - [devtools] Create target actors for all iframes.

* devtools.netmonitor.features.newEditAndResend
Bug [1744759](https://bugzilla.mozilla.org/show_bug.cgi?id=1744759) - [devtools] Create a pref flag for the edit and resend panel.

* devtools.webconsole.input.context
Bug [1731740](https://bugzilla.mozilla.org/show_bug.cgi?id=1731740) - [devtools] Enable EFT by default.

* dom.ipc.plugins.sandbox-level.default
Bug [1742312](https://bugzilla.mozilla.org/show_bug.cgi?id=1742312) removed NPAPI related flags
Bug [1722412](https://bugzilla.mozilla.org/show_bug.cgi?id=1722412) - Remove Mac Flash Sandboxing Prefs

* dom.ipc.plugins.sandbox-level.flash
Bug [1742312](https://bugzilla.mozilla.org/show_bug.cgi?id=1742312) removed NPAPI related flags
Bug [1722412](https://bugzilla.mozilla.org/show_bug.cgi?id=1722412) - Remove Mac Flash Sandboxing Prefs

* dom.quotaManager.temporaryStorage.chunkSize
Bug [1735713](https://bugzilla.mozilla.org/show_bug.cgi?id=1735713) - Revamp temporary storage limits;

* dom.screenorientation.allow-lock
Bug [1697647](https://bugzilla.mozilla.org/show_bug.cgi?id=1697647) - Add screen orientation lock api

* dom.securecontext.allowlist_onions
Bug [1744006](https://bugzilla.mozilla.org/show_bug.cgi?id=1744006) - Replace dom.securecontext.whitelist_onions with dom.securecontext.allowlist_onions and dom.securecontext.whitelist with dom.securecontext.allowlist

* dom.securecontext.whitelist_onions
Bug [1744006](https://bugzilla.mozilla.org/show_bug.cgi?id=1744006) - Replace dom.securecontext.whitelist_onions with dom.securecontext.allowlist_onions and dom.securecontext.whitelist with dom.securecontext.allowlist

* dom.svg.pathSeg.enabled
Bug [1388931](https://bugzilla.mozilla.org/show_bug.cgi?id=1388931) - Unship SVGPathSeg APIs behind a preference.

* dom.vr.enabled
Bug [1750902](https://bugzilla.mozilla.org/show_bug.cgi?id=1750902) - Disable dom.vr.enabled by default.

* dom.w3c_pointer_events.dispatch_by_pointer_messages
Bug [1707075](https://bugzilla.mozilla.org/show_bug.cgi?id=1707075) - Enable dispatch_by_pointer_messages by default

* dom.webmidi.gated
Bug [1742471](https://bugzilla.mozilla.org/show_bug.cgi?id=1742471) enforce addon gating of webmidi interfaces

* editor.background_color
Bug [1745882](https://bugzilla.mozilla.org/show_bug.cgi?id=1745882) - Move all editor prefs in `all.js` to `StaticPrefList.yaml`

* editor.hr_element.allow_to_delete_from_following_line
Bug [1745879](https://bugzilla.mozilla.org/show_bug.cgi?id=1745879) - Allow to delete `&lt;hr&gt;` element with a `Backspace` key press from next line of it

* extensions.pocket.refresh.emailButton.enabled
Bug [1746027](https://bugzilla.mozilla.org/show_bug.cgi?id=1746027) - Save to Pocket refresh prefs and Nimbus implementation

* extensions.pocket.refresh.layout.enabled
Bug [1746027](https://bugzilla.mozilla.org/show_bug.cgi?id=1746027) - Save to Pocket refresh prefs and Nimbus implementation

* fission.autostart
Bug [1732358](https://bugzilla.mozilla.org/show_bug.cgi?id=1732358) - Part 4: Enable fission by default on non-android platforms,
Bug [1674871](https://bugzilla.mozilla.org/show_bug.cgi?id=1674871): Unlock fission.autostart and allow to ride the trains.

* fission.openNonFissionWindowOption
Bug [1661791](https://bugzilla.mozilla.org/show_bug.cgi?id=1661791) - Remove &quot;New Non-Fission Window&quot; menu item.

* gfx.webrender.dcomp-video-overlay-win
Bug [1746065](https://bugzilla.mozilla.org/show_bug.cgi?id=1746065) - Use a static pref for dcomp overlay.

* intl.hyphenation-alias.as
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.as-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.bn-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.gu-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.hi-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.kn-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.ml-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.mr
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.mr-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.or-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.pa-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.ta-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* intl.hyphenation-alias.te-*
Bug [1240277](https://bugzilla.mozilla.org/show_bug.cgi?id=1240277) - Add hyphenation patterns for Indic languages.

* layers.acceleration.draw-fps
Bug [1745109](https://bugzilla.mozilla.org/show_bug.cgi?id=1745109) - Remove DiagnosticsD3D11

* layout.css.cascade-layers.enabled
Bug [1699215](https://bugzilla.mozilla.org/show_bug.cgi?id=1699215) - Enable cascade layers everywhere.

* layout.css.d-property.enabled
Bug [1744599](https://bugzilla.mozilla.org/show_bug.cgi?id=1744599) - Ship d property.

* layout.css.hyphenate-character.enabled
Bug [1746187](https://bugzilla.mozilla.org/show_bug.cgi?id=1746187) - Add CSS support for the hyphenate-character property.

* layout.css.named-pages.enabled
Bug [1741973](https://bugzilla.mozilla.org/show_bug.cgi?id=1741973) - Implement parsing of the page property

* layout.css.scrollbar-gutter.enabled
Bug [1715112](https://bugzilla.mozilla.org/show_bug.cgi?id=1715112) Part 3 - Enable CSS scrollbar-gutter by default.
Bug [1741774](https://bugzilla.mozilla.org/show_bug.cgi?id=1741774) - Support scrollbar-gutter in the style system.

* layout.css.touch_action.enabled
Bug [1748174](https://bugzilla.mozilla.org/show_bug.cgi?id=1748174) - Remove touch-action pref.

* layout.oopif_activity_grace_period_ms
Bug [1745869](https://bugzilla.mozilla.org/show_bug.cgi?id=1745869) - Grant 1s of activity to hidden OOPIF iframes.

* layout.throttled_frame_rate
Bug [1746229](https://bugzilla.mozilla.org/show_bug.cgi?id=1746229) - Minor cleanups to the refresh driver.

* layout.visibility.min-recompute-interval-ms
Bug [1746229](https://bugzilla.mozilla.org/show_bug.cgi?id=1746229) - Minor cleanups to the refresh driver.

* media.audio.playbackrate.muting_threshold
Bug [1630569](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) - Change the limit at which audio is muted with high or low playback rates, and make it and other parameters configurable via prefs.

* media.audio.playbackrate.soundtouch_overlap_ms
Bug [1630569](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) - Change the limit at which audio is muted with high or low playback rates, and make it and other parameters configurable via prefs.

* media.audio.playbackrate.soundtouch_seekwindow_ms
Bug [1630569](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) - Change the limit at which audio is muted with high or low playback rates, and make it and other parameters configurable via prefs.

* media.audio.playbackrate.soundtouch_sequence_ms
Bug [1630569](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) - Change the limit at which audio is muted with high or low playback rates, and make it and other parameters configurable via prefs.

* media.videocontrols.picture-in-picture.allow-multiple
Bug [1739515](https://bugzilla.mozilla.org/show_bug.cgi?id=1739515) - Remove checks for multiple PiP windows pref
Bug [1687477](https://bugzilla.mozilla.org/show_bug.cgi?id=1687477): Enable multiple Picture-in-Picture support by default
Bug [1589680](https://bugzilla.mozilla.org/show_bug.cgi?id=1589680): Added support for multiple, concurrent Picture-in-Picture windows

* media.videocontrols.picture-in-picture.video-toggle.visibility-threshold
Bug [1742585](https://bugzilla.mozilla.org/show_bug.cgi?id=1742585) - Add PiP toggle visibility threshold preference

* media.webrtc.platformencoder
Bug [1747913](https://bugzilla.mozilla.org/show_bug.cgi?id=1747913) - turn on platform encoder and software fallback pref on all supported platforms.
Bug [1654112](https://bugzilla.mozilla.org/show_bug.cgi?id=1654112) - Adapt VideoConduit to the new libwebrtc version.

* media.webrtc.software_encoder.fallback
Bug [1747913](https://bugzilla.mozilla.org/show_bug.cgi?id=1747913) - turn on platform encoder and software fallback pref on all supported platforms.
Bug [1726617](https://bugzilla.mozilla.org/show_bug.cgi?id=1726617) - p1: use video encoder fallback wrapper in WebRTC.

* network.auth.choose_most_secure_challenge
Bug [650091](https://bugzilla.mozilla.org/show_bug.cgi?id=650091) - Sort authentication challenges by safety rating

* network.cookie.sameSite.laxByDefault
Bug [1751435](https://bugzilla.mozilla.org/show_bug.cgi?id=1751435) - sameSite=lax, noneRequiresSecure and samesiteSchemeful in early beta or earlier
Bug [1617609](https://bugzilla.mozilla.org/show_bug.cgi?id=1617609): Enable sameSite=lax by default.

* network.cookie.sameSite.noneRequiresSecure
Bug [1751435](https://bugzilla.mozilla.org/show_bug.cgi?id=1751435) - sameSite=lax, noneRequiresSecure and samesiteSchemeful in early beta or earlier
Bug [1750264](https://bugzilla.mozilla.org/show_bug.cgi?id=1750264) - Disable cookie sameSite schemeful in Firefox 96.
Bug [1617609](https://bugzilla.mozilla.org/show_bug.cgi?id=1617609): Enable sameSite=lax by default.

* network.cookie.sameSite.schemeful
Bug [1751435](https://bugzilla.mozilla.org/show_bug.cgi?id=1751435) - sameSite=lax, noneRequiresSecure and samesiteSchemeful in early beta or earlier
Bug [1750264](https://bugzilla.mozilla.org/show_bug.cgi?id=1750264) - Disable cookie sameSite schemeful in Firefox 96.
Bug [1617609](https://bugzilla.mozilla.org/show_bug.cgi?id=1617609): Enable sameSite=lax by default.

* network.proxy.allow_bypass
Bug [1733481](https://bugzilla.mozilla.org/show_bug.cgi?id=1733481) retry telemetry requests when a proxy fails

* network.url.max-length
Bug [1741426](https://bugzilla.mozilla.org/show_bug.cgi?id=1741426) - Ship network.url.max-length = 32Mb dataURL limit to release

* print.cups.enum_dests_timeout_ms
Bug [1747952](https://bugzilla.mozilla.org/show_bug.cgi?id=1747952) - Include discovered/network printers in the CUPS list, with a timeout.

* print.show_page_setup_menu
Bug [1745465](https://bugzilla.mozilla.org/show_bug.cgi?id=1745465) - Add a pref to enable the Page Setup menu.

* print.tab_modal.enabled
Bug [1702501](https://bugzilla.mozilla.org/show_bug.cgi?id=1702501) - Remove print.tab_modal.enabled pref and old frontend print preview code.

* privacy.antitracking.cacheStorageAllowedForWindow
Bug [1745039](https://bugzilla.mozilla.org/show_bug.cgi?id=1745039) - Remove privacy.antitracking.cacheStorageAllowedForWindow pref.

* ui.key.textcontrol.prefer_native_key_bindings_over_builtin_shortcut_key_definitions
Bug [1747326](https://bugzilla.mozilla.org/show_bug.cgi?id=1747326) - Enable the fix for bug [1743339](https://bugzilla.mozilla.org/show_bug.cgi?id=1743339) and bug [1743346](https://bugzilla.mozilla.org/show_bug.cgi?id=1743346) by default in the Beta/Release channels too
Bug [1743346](https://bugzilla.mozilla.org/show_bug.cgi?id=1743346) - Make `TextInputHandler::HandleEvent` handle native key bindings first, then, our shortcut keys

* widget.disable-swipe-tracker
Bug [1751124](https://bugzilla.mozilla.org/show_bug.cgi?id=1751124) - Disable SwipeTracker on Windows.

* widget.non-native-theme.win11.scrollbar.force-overlay-style
Bug [1747618](https://bugzilla.mozilla.org/show_bug.cgi?id=1747618) - Implement non-overlay scrollbar style for Win11.

</p></details>
