### ISSUE TITLE
Possible Small Enhancements

### ISSUE THREAD

**Issue by Jmkrnet** [arkenfox/user.js#1747]
When upgrading to Firefox (FF) ESR 102 and now to ESR 115 I have accumulated some small enhancements (all should apply to current "user.js" version 118):

edited by 🩳

---

SECTION 0800 or 5000 or 9000 MAYBE ADD:
Adds calculator for basic math calculations to address bar. For example typing "1+1" to address bar gives result "= 2" and it works offline without connecting to any search engines.
// user_pref("browser.urlbar.suggest.calculator", true);

DONE
- [x] declined

---

0211 POSSIBLY REMOVE AS IT SEEMS TO BE HANDLED BY RFP (AND MAYBE 0210 IS ALSO REDUNDANT?):
- This preference seems to me like it was removed from Firefox:
  - I was unable to find it using Searchfox (https://searchfox.org/mozilla-central/search?q=javascript.use_us_english_locale&path=&case=false&regexp=false).
  - The whole language spoofing mehanism seems to be handled by RFP for some time now:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1369330
  https://bugzilla.mozilla.org/show_bug.cgi?id=1039069
  https://bugzilla.mozilla.org/show_bug.cgi?id=1846224
  https://bugzilla.mozilla.org/show_bug.cgi?id=1629630
  - For example the preference is no longer used in "_handleSpoofEnglishChanged()":
  https://searchfox.org/mozilla-central/source/toolkit/components/resistfingerprinting/RFPHelper.sys.mjs#163
  https://hg.mozilla.org/mozilla-central/rev/4036881d8ab0

DONE
- [x] is deprecated in FF119
- [x] 0210 becomes useless (will remove) - done, see #1759 

---

1006 POSSIBLE COMMENT ENHANCEMENT:
- I was not able to make this work on LINUX with FF ESR 102. Link shortcuts created by dragging URL from address bar to desktop are always (i.e. with the pref set to false or true) created with a generic icon and there is no "shortcutCache" or similar directory with "*.ico" files in FF profile or cache directories. Seems to me like it is a WINDOWS only feature (some summary info: https://quantumwarp.com/kb/articles/31-media/935-windows-firefox-favicon-internet-shortcuts-and-caching)?
- I did not test this again on FF ESR 115, but it probably did not change.

DONE
- [x] add `[WINDOWS]` tag - see https://github.com/arkenfox/user.js/pull/1757/commits/958e56a21aab2a016932d1adb1541284ee538c06 and https://github.com/arkenfox/user.js/issues/1747#issuecomment-1791749797

---

2603.helperApps.deleteTempFileOnExit, 2815.cookies POSSIBLE COMMENT ENHANCEMENT:
- Seems to be true by default at least on my OS (LINUX) with FF ESR 102 and 115.
- POSSIBLE TEXT TO ADD IF CONFIRMED: [DEFAULT true]

DONE
- [x] confirmed differs per platform no action taken: see https://github.com/arkenfox/user.js/issues/1747#issuecomment-1791400860

---

5508.eme.enabled POSSIBLE COMMENT ENHANCEMENT:
- Seems to be false by default at least on my OS (LINUX) with FF ESR 102 and 115.
- POSSIBLE TEXT TO ADD IF CONFIRMED: [DEFAULT false]

DONE
- [x] is default true on windows. I only add default notations if I need to for active prefs, or if it's the same on all desktop platforms. The less shit to track and keep up to date the better

---

2660 POSSIBLE COMMENT ENHANCEMENT:
- Scopes are described also in FF source code (see: https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#55).
- The "AddonManager.jsm" changed to "AddonManager.sys.mjs" in FF 115 (https://bugzilla.mozilla.org/show_bug.cgi?id=1836482).
- POSSIBLE TEXT TO ADD: See the SCOPE constants in "AddonManager.sys.mjs" for values to use here.
- POSSIBLE LINK TO ADD: https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManager.sys.mjs#4142

DONE
- [x] add what values stand for: see https://github.com/arkenfox/user.js/issues/1747

---

I am not sure how you define hidden prefs, but if it means non-obsolete prefs that are not visible in "about:config" unless FF or user defines some value for them (i.e. a "Delete" instead of "Reset" button is shown in "about:config"), here are prefs I noticed not marked as "[HIDDEN PREF]" that seem to be hidden at least on my OS (LINUX) with FF ESR 102 and 115:
- user_pref("browser.startup.homepage_override.mstone", "ignore");
- user_pref("extensions.webcompat.enable_shims", true);
- user_pref("browser.contentblocking.category", "strict");
- user_pref("geo.provider.use_gpsd", false);

DONE
- [x] these are all runtime, set by the browser, so whilst technically "hidden" (see next comment below), they're not really because they will always have a value in about:config. But will notate regardless to be consistent

**Comment by Thorin-Oakenpants** [comment]
- `browser.urlbar.suggest.calculator` - has nothing to do with this repo - privacy/tracking/etc
- `javascript.use_us_english_locale`
   - is deprecated in FF119 - which is why you won't find it on searchfox
   - RFP no longer protects your locale (and it was limited to en-US with that pref)
   - at some stage they will hook up locale to match language in some form, which will be better

hidden pref
 - it does not show in about:config unless modified (regardless of the value, it is modified)

**Comment by Thorin-Oakenpants** [comment]
helperApps.deleteTempFileOnExit - is default true on windows as well

**Comment by Thorin-Oakenpants** [comment]
https://searchfox.org/mozilla-central/search?q=helperApps.deleteTempFileOnExit&path=&case=false&regexp=false

helperApps.deleteTempFileOnExit - true in firefox.js, false in all.js  ... how does this work (rhetorical)?

ignoring android (FYI: @SkewedZeppelin) I guess we just test each platform
- linux is true (but packagers could change it)
- windows is true
- mac (FF119) is false <-- assuming it even applies to mac

So I think we can ignore adding a default note

**Comment by Thorin-Oakenpants** [comment]
`browser.shell.shortcutFavicons`
- https://searchfox.org/mozilla-central/search?q=browser.shell.shortcutFavicons&path=&case=false&regexp=false
   - only has code for `widget/windows`, i.e not `widget/cocoa` or `widget/gtk` etc

So yup, I would say this is a windows only thing

**Comment by Thorin-Oakenpants** [comment]
scopes
- https://hg.mozilla.org/integration/autoland/file/909b53b0ab300dcaaed44f901c55eefc8abdb721/toolkit/mozapps/extensions/AddonManager.sys.mjs#l4104 <-- use the commit source so lines don't get fucked up over time

man that's a long one. I use searchfox links to files, but hg.mozilla.org revisions links to lines - but this revision moved the file and didn't change it, so I can't use a sweet short link

lets see what the diffs are:

kaply
```
1 (SCOPE_PROFILE)
2 (SCOPE_USER)
4 (SCOPE_APPLICATION)
8 (SCOPE_SYSTEM)
```

moz code
```
  // General descriptions of where items are installed.
  // Installed in this profile.
  SCOPE_PROFILE: 1,
  // Installed for all of this user's profiles.
  SCOPE_USER: 2,
  // Installed and owned by the application.
  SCOPE_APPLICATION: 4,
  // Installed for all users of the computer.
  SCOPE_SYSTEM: 8,
  // Installed temporarily
  SCOPE_TEMPORARY: 16,
  // The combination of all scopes.
  SCOPE_ALL: 31,
```

yeah, so that's a good link to add, because that archive is fucking old now and somewhat out of date

**Comment by Thorin-Oakenpants** [comment]
actually, fuck that long link ;) it hasn't changed anything, because temporary extensions cannot load on restart.. and I can just add this

```
 * 1=profile, 2=user, 4=application, 8=system, 16=temporary, 31=all
```

**Comment by Thorin-Oakenpants** [comment]
`extensions.webcompat.enable_shim` - is runtime - set based on ETP settings = so not hidden, but technically it is hidden

**Comment by Thorin-Oakenpants** [comment]
^ repeat - someone answer ... starting to feel like my childhood in the basement again

**Comment by SkewedZeppelin** [comment]
maybe managed?

**Comment by Thorin-Oakenpants** [comment]
not sure if I want another tag

so here's the thing - I label items to help, but that doesn't mean I have to label ALL items that fit that tag: eg
- not all items have a `[FFversion+]` - although that's mostly really old prefs
- not all items have a `[DEFAULT: ` - and maintaining it is a burden, especially when it differs per OS
- etc

So i kinda feel like these items that aren't "hidden" in about:config don't really need a `[HIDDEN]` tag - but I get that as a purist, it is fine. And if someone says "but it's not hidden" I can use the same definition I always have, and then tell them to delete it and reload about:config and tell if they can see it

So the question is - do I add hidden tags or not?

**Comment by Thorin-Oakenpants** [comment]
And if I don;t label them, then if someone says .. but that's a HIDDEN pref, please label it - I can say "I only label them when they aren't set by runtime to help users"

So I win either way

So do I add the labels or not ... quick poll of one .. you're up Tad

**Comment by Thorin-Oakenpants** [comment]
ok, ignoring them, because of maintenance, plus I am the boss so my second argument wins. just need to check that geo one - because that may only get set if the system supports it

**Comment by crssi** [comment]
> starting to feel like my childhood in the basement again

I know this response is a "spam", but you seems to make me laugh quite a lot of time. Love you

**Comment by Thorin-Oakenpants** [comment]
> I know this response is a "spam", but you seems to make me laugh quite a lot of time. Love you

It wasn't _all_ bad ... I had regular nightly visits from Father Duffy, Father Brown, Father O'Brien ... all of them actually

**Comment by Thorin-Oakenpants** [comment]
might revisit my last decision .. I mean if it universally (all desktop platforms) has a trash bin symbol, then it's [HIDDEN]

**Comment by Thorin-Oakenpants** [comment]
okie dokie
- I updated the wiki description of `hidden` - https://github.com/arkenfox/user.js/wiki/2.1-User.js
   - > except for what are called `hidden preferences` which will only show when they are `modified` (i.e. set to any value by the user or browser - they have a trash can symbol for resetting)
- have updated notation on the prefs in user.js - https://github.com/arkenfox/user.js/pull/1757/commits/ac9f82a11516ea4e83ccce6c35c7679410f929dc

@Jmkrnet thanks .. have some 🍰 or 🥧
